### ISSUE TITLE
ContextFlyout Button does not work

### ISSUE THREAD

**Issue by furesoft** [AvaloniaCommunity/Material.Avalonia#107]
If I use default Button it works fine. If I use classes Flat it does not appear

**Comment by SKProCH** [comment]
Hello, @furesoft 

I've implemented Flyouts support. 

You can [install and use](https://github.com/AvaloniaCommunity/Material.Avalonia/wiki/Using-nightly-build-feed) latest nightly version [nuget](https://github.com/AvaloniaCommunity/Material.Avalonia/packages/572265) or wait until stable version of package has been released on Nuget feed.
