### ISSUE TITLE
MenuItem.DataTemplates brakes default template/style

### ISSUE THREAD

**Issue by dojo90** [AvaloniaCommunity/Material.Avalonia#119]
When using a `DataTemplate` for the `MenuItem` to dynamically create the `Menu`, the default style seems to be broken

![grafik](https://user-images.githubusercontent.com/17551597/137912294-b06cc9ab-a5c6-46f3-bd53-ec06e7b83fbc.png)

```xaml
<Menu Grid.Column="4" Height="32" Padding="0" Margin="0">
  <MenuItem Height="32" Width="32" Name="FuncMenuItem" Header="{avalonia:MaterialIconExt DotsVertical, Size=24}">
	<MenuItem.DataTemplates>
	  <DataTemplate DataType="app:FuncMenuCommandItem">
		<MenuItem Header="{Binding Name}" Command="{Binding Command}" CommandParameter="{Binding CommandParameter}">
		  <MenuItem.Icon>
			<avalonia:MaterialIcon Kind="{Binding Icon}" Width="24" Height="24" />
		  </MenuItem.Icon>
		</MenuItem>
	  </DataTemplate>
	  <DataTemplate DataType="app:FuncMenuSeparatorItem">
		<Separator/>
	  </DataTemplate>
	</MenuItem.DataTemplates>
  </MenuItem>
</Menu>
```

![grafik](https://user-images.githubusercontent.com/17551597/137912671-6a64dac3-07e3-47f7-b279-20316bc5f907.png)

while using the default xaml definition from the `Material.Demo` application, looks fine.

![grafik](https://user-images.githubusercontent.com/17551597/137912823-d5212717-f2ca-4ce3-b71f-68783255215c.png)

```xaml
<Menu Grid.Column="4" Height="32" Padding="0" Margin="0">
  <MenuItem Height="32" Width="32" Name="FuncMenuItem" Header="{avalonia:MaterialIconExt DotsVertical, Size=24}">
	<MenuItem Header="Hello!" Click="HelloButtonMenuItem_OnClick">
	  <MenuItem.Icon>
		<avalonia:MaterialIcon Kind="Hand" Width="24" Height="24" />
	  </MenuItem.Icon>
	</MenuItem>
	<Separator />
	<MenuItem Header="Action 1" />
	<MenuItem Header="Action 2" />
	<MenuItem Header="Action 3" />
	<Separator />
	<MenuItem Header="Goodbye" Click="GoodbyeButtonMenuItem_OnClick">
	  <MenuItem.Icon>
		<avalonia:MaterialIcon Kind="ExitRun" Width="24" Height="24" />
	  </MenuItem.Icon>
	</MenuItem>
  </MenuItem>
</Menu>
```

Actually I don't know what's wrong with my code 🤔

**Comment by SKProCH** [comment]
Hello, @dojo90 

Sorry for long answer.
I figured out whats wrong with this situation. Actually MenuItem.DataTemplate sets template for MenuItem header, nor for all MenuItem content.
So, when you apply your style you get MenuItems inside of your MenuItem.
![image](https://user-images.githubusercontent.com/29896317/140660582-9d445813-a136-4b22-87fa-2df02d923f76.png)
So, spaces at left this is space for Icon and margin, space from right - margin.
![image](https://user-images.githubusercontent.com/29896317/140658742-87397ed2-6e8c-4c09-9735-9175c836fd3a.png)
As the solution if you can need separators and menu items generated from you models you need to create controls by yourself (or via behavior, attached property, etc). DataTemplate not intended for such use.

Feel free to reopen issue if you have any questions.

**Comment by dojo90** [comment]
Thanks for the hint, I have now been able to solve the problem by creating the MenuItems in the code behind. 👍

<details>
  <summary>Code</summary>

```cs
// FuncMenu
var funcMenuBuilder = App.Container.GetRequiredService<IFuncMenuBuilder>();
// https://github.com/AvaloniaCommunity/Material.Avalonia/issues/119
// FuncMenuItem.Items = funcMenuBuilder.FuncMenuItems;
var items = new ObservableCollection<TemplatedControl>();
foreach (var item in funcMenuBuilder.FuncMenuItems)
{
	switch (item)
	{
		case FuncMenuSeparatorItem funcMenuSeparatorItem:
			items.Add(new Separator());
			break;
		case FuncMenuCommandItem funcMenuCommandItem:
			var mi = new MenuItem
				{
					Header = funcMenuCommandItem.Name,
					Command = funcMenuCommandItem.Command,
					CommandParameter = funcMenuCommandItem.CommandParameter,
					Icon = new MaterialIcon
					{
						Kind = funcMenuCommandItem.Icon
					}
				};
			items.Add(mi);
			break;
		default:
			throw new ArgumentOutOfRangeException(nameof(item));
	}
}

FuncMenuItem.Items = items;
```
  
</details>

If I can only define the header with the DataTemplate, what is it intended for or what do I need the DataTemplate for?

Unfortunately I cannot reopen the issue.

**Comment by SKProCH** [comment]
Okay, I'm glad you were able to solve your problem.

> If I can only define the header with the DataTemplate, what is it intended for or what do I need the DataTemplate for? 

I don't know what is the purpose of using DataTemplate for Header. Perhaps Header is supposed to be more than just a string as content, depending on the type of the object for example. 
But, at least it works in the same way in Avalonia itself, conceptually we have not changed anything.
Avalonia MenuItem [style](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml#L87)
Material.Avalonia MenuItem [style](https://github.com/AvaloniaCommunity/Material.Avalonia/blob/dev/Material.Styles/MenuItem.xaml#L55)
