### ISSUE TITLE
How can I override MaterialDesignDarkBackground in my app ?

### ISSUE THREAD

**Issue by flarive** [AvaloniaCommunity/Material.Avalonia#120]
Hello,

I would like to use the Material Dark theme with a darker background color.
Is there a way to override the default value of MaterialDesignDarkBackground SolidColorBrush please ?

Thanks a lot !

Eviral

**Comment by SKProCH** [comment]
Hello, @flarive 

I took a quick look and found a solution. Edit your `App.axaml` file, Application.Resources section, so it will looks like: 
```
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <themes:BundledTheme BaseTheme="Light" PrimaryColor="Teal" SecondaryColor="Amber"/>
            <ResourceDictionary>
                <Color x:Key="MaterialDesignDarkBackground">Black</Color>
            </ResourceDictionary>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```
And, if you want to change background color (eg. window background) you need to change `MaterialDesignPaper` key.

**Comment by SKProCH** [comment]
Also, this solution will work only for initial theme (which been set in BundledTheme component). If you change theme in runtime (via PaletteHelper) your changes will be overwritten.  
I will continue to investigate this situation, but due to the fact that my main time is spent on work, this can be a long time.

**Comment by flarive** [comment]
Hi, thanks a lot for your answer...
I have tried, but it does'n't work...
I have tried to replace your Color: with SolidColorBrush: because MaterialDesignDarkBackground is a brush and not a color in your code, but it doesn't work...
Your built in style in not overrided by the app.xaml style.

<Application.Resources>
		<ResourceDictionary>
			<locators:ViewModelLocator x:Key="ViewModelLocator"/>
			<ResourceDictionary.MergedDictionaries>
				<themes:BundledTheme BaseTheme="Dark" PrimaryColor="Blue" SecondaryColor="Amber"/>
				
				<ResourceDictionary>
					<SolidColorBrush x:Key="MaterialDesignDarkBackground" Color="White"/>
				</ResourceDictionary>
				<ResourceInclude Source="/Styles/Styles.xaml"/>
			</ResourceDictionary.MergedDictionaries>
		</ResourceDictionary>
	</Application.Resources>

**Comment by SKProCH** [comment]
Hmm, i figured it out, @flarive 
If you want to change any of this brushes: 
![image](https://user-images.githubusercontent.com/29896317/141445074-3f142665-1316-49d0-b90c-cfe76ef2963a.png)
You need to add something like this in your Application.Styles section: 
```
      <Style>
          <Style.Resources>
              <SolidColorBrush x:Key="MaterialDesignDarkBackground" Color="Red"/>
          </Style.Resources>
      </Style>
```
So, it will looks like this:
![image](https://user-images.githubusercontent.com/29896317/141445224-4d8ab2c2-88b7-4d1b-952d-91586b320ed2.png)

**Comment by flarive** [comment]
Argg...
Sorry but it still doesn't work, nothing is overrided.

`<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:locators="using:MaterialLogReader.Locators"
			 xmlns:themes="clr-namespace:Material.Styles.Themes;assembly=Material.Styles"
			 xmlns:assists="clr-namespace:Material.Styles.Assists;assembly=Material.Styles"
			 xmlns:ripple="clr-namespace:Material.Ripple;assembly=Material.Ripple"
             x:Class="MaterialLogReader.App">

	<Application.Resources>
		<ResourceDictionary>
			<locators:ViewModelLocator x:Key="ViewModelLocator"/>
			<ResourceDictionary.MergedDictionaries>
				<themes:BundledTheme BaseTheme="Dark" PrimaryColor="Blue" SecondaryColor="Amber"/>
				
				<ResourceInclude Source="/Styles/Styles.xaml"/>
			</ResourceDictionary.MergedDictionaries>
		</ResourceDictionary>
	</Application.Resources>

	<Application.Styles>
		
		<StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>
		<StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseDark.xaml"/>
		
		<StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Default.xaml"/>
		<StyleInclude Source="avares://Material.Avalonia/Material.Avalonia.Templates.xaml" />
		<StyleInclude Source="avares://Material.Icons.Avalonia/App.xaml"/>
		<StyleInclude Source="/Styles/Material.DataGrid.xaml"/>
		
		<StyleInclude Source="/Styles/CustomStyles.xaml"/>
		<StyleInclude Source="/Styles/Icons.axaml"/>
		<Style>
			<Style.Resources>
				<SolidColorBrush x:Key="MaterialDesignDarkBackground" Color="Red"/>
			</Style.Resources>
		</Style>
	</Application.Styles>
</Application>`

**Comment by SKProCH** [comment]
Hmm, if i drop your app.xaml content to demo app (excluding some styles that non exists in demo app) and i setup explicit bind to MaterialDesignDarkBackground i will get red color:  
![image](https://user-images.githubusercontent.com/29896317/141519796-10b5cf4e-9473-4ee6-9463-9c9f0a26d356.png)  
![image](https://user-images.githubusercontent.com/29896317/141519851-48c4b6a9-4a71-4f36-993f-508850247f6e.png)  
![image](https://user-images.githubusercontent.com/29896317/141519908-853f907d-fbc9-4dff-aab8-c016fe79cae8.png)

So, are you sure what you don't using `PaletteHelper` and materials theme changing at runtime?

Are you sure what you need to set `MaterialDesignDarkBackground`? **Because this brush (MaterialDesignDarkBackground) not used for actual windows background theming** and etc! This brushes (MaterialDesignLightBackground, MaterialDesignLightForeground, MaterialDesignDarkBackground, MaterialDesignDarkForeground) are used to get theme independent colors. If you need to change, for example, window background you need to change value of `MaterialDesignPaper` brush.  
If so, then you need to change Application.Resources like this:
```
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <themes:BundledTheme BaseTheme="Dark" PrimaryColor="Blue" SecondaryColor="Amber"/>
            <ResourceDictionary>
                <SolidColorBrush x:Key="MaterialDesignPaper" Color="Red"/>
            </ResourceDictionary>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```
And, then you get your color as Window background: 
![image](https://user-images.githubusercontent.com/29896317/141521470-2e7da7b0-5235-4c6c-9753-891f210835d4.png)

**Comment by flarive** [comment]
Yes ! It works now with 
`<ResourceDictionary>
    <SolidColorBrush x:Key="MaterialDesignPaper" Color="Red"/>
</ResourceDictionary>`

I'm using PaletteHelper to let user choose between dark and light theme 👍 

`        private void ApplyMaterialUIDarkTheme()
        {
            var theme = PaletteHelper.GetTheme();
            theme.SetPrimaryColor(SwatchHelper.Lookup[MaterialColor.Blue200]);
            theme.SetSecondaryColor(SwatchHelper.Lookup[MaterialColor.Pink200]);
            theme.SetBaseTheme(BaseThemeMode.Dark.GetBaseTheme());
            PaletteHelper.SetTheme(theme);
        }
        
        private void ApplyMaterialUILightTheme()
        {
            var theme = PaletteHelper.GetTheme();
            theme.SetPrimaryColor(SwatchHelper.Lookup[MaterialColor.Blue]);
            theme.SetSecondaryColor(SwatchHelper.Lookup[MaterialColor.Pink400]);
            theme.SetBaseTheme(BaseThemeMode.Light.GetBaseTheme());
            PaletteHelper.SetTheme(theme);
        }`

My last problem now is how can use PaletteHelper to let user change theme at runtime and to keep my custom dark background #ff11191f when user switch themes at runtime ?

Thanks a lot for your help ! Really !!!

**Comment by SKProCH** [comment]
> My last problem now is how can use PaletteHelper to let user change theme at runtime and to keep my custom dark background #ff11191f when user switch themes at runtime ?
So far, this is not possible for technical reasons. I am currently looking for a way to fix this.

**Comment by flarive** [comment]
Great !
Why don't you just let the developer customize the dark background color and the light background color with 2 new properties in : 
<themes:BundledTheme BaseTheme="Dark" PrimaryColor="Blue" SecondaryColor="Amber"/>
?

**Comment by SKProCH** [comment]
I fixed this bug in 25b8940. You can try it in [2.4.1.27-nightly](https://www.nuget.org/packages/Material.Avalonia/2.4.1.27-nightly) package version.
```xaml
<Application.Resources>
    <ResourceDictionary>
        <SolidColorBrush x:Key="MaterialDesignPaper" Color="Red"/>
        <ResourceDictionary.MergedDictionaries>
            <themes:BundledTheme BaseTheme="Light" PrimaryColor="Teal" SecondaryColor="Amber"/>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```

Also i add more complex theme settings later.

**Comment by flarive** [comment]
Thanks a lot, it works, when i change to dark theme at runtime my custom MaterialDesignPaper remains but it also remains when i apply light theme at runtime :(
I have no light theme anymore because MaterialDesignPaper always override everything.
So sorry...

**Comment by SKProCH** [comment]
Hmm, you can set your color in Theme before applying it via `PaletteHelper.SetTheme(theme);`.
But you should call theme applying at startup to change default color to your color

**Comment by flarive** [comment]
Yes, it works !

`private void ApplyTheme()
        {
            object? paperColorBrush = null;
            App.Current.Resources.MergedDictionaries[1].TryGetResource("MaterialDesignPaper", out paperColorBrush);

            if (UseDarkTheme)
            {
                ApplyMaterialUIDarkTheme();

                if (paperColorBrush is SolidColorBrush)
                {
                    ((SolidColorBrush)paperColorBrush).Color = Color.Parse("#ff11191f");
                }
            }
            else
            {
                ApplyMaterialUILightTheme();


                if (paperColorBrush is SolidColorBrush)
                {
                    ((SolidColorBrush)paperColorBrush).Color = Colors.White; 
                }
     
            }
        }`

**Comment by SKProCH** [comment]
@flarive, actually you can simplify code just by editing ApplyMaterialUILightTheme and ApplyMaterialUIDarkTheme:
```
private void ApplyMaterialUIDarkTheme()
{
    var theme = PaletteHelper.GetTheme();
    theme.SetPrimaryColor(SwatchHelper.Lookup[MaterialColor.Blue200]);
    theme.SetSecondaryColor(SwatchHelper.Lookup[MaterialColor.Pink200]);
    theme.SetBaseTheme(BaseThemeMode.Dark.GetBaseTheme());
    theme.Paper = Color.Parse("#ff11191f");
    PaletteHelper.SetTheme(theme);
}

private void ApplyMaterialUILightTheme()
{
    var theme = PaletteHelper.GetTheme();
    theme.SetPrimaryColor(SwatchHelper.Lookup[MaterialColor.Blue]);
    theme.SetSecondaryColor(SwatchHelper.Lookup[MaterialColor.Pink400]);
    theme.SetBaseTheme(BaseThemeMode.Light.GetBaseTheme());
    theme.Paper = Colors.White;
    PaletteHelper.SetTheme(theme);
}
```
