### ISSUE TITLE
How use DialogHelper.CreateCustomDialog ?

### ISSUE THREAD

**Issue by Maruhl** [AvaloniaCommunity/Material.Avalonia#121]
I create the CustomDialogBuilderParams with a method that looks like this:

```
	private static CustomDialogBuilderParams CreateBaseCustomDialogParams(IDialogBaseViewModel viewModel)
	{
		return new CustomDialogBuilderParams
		{
			ContentHeader = viewModel.Caption,
			Content = viewModel,
			Borderless = true,
			StartupLocation = WindowStartupLocation.CenterOwner
		};
	}
```

The result:
![grafik](https://user-images.githubusercontent.com/41585619/141513973-9eeacab7-7aab-4271-ab75-b155540de8c1.png)

The custom dialog system seems to completely ignore the logic of the Avalonia ViewLocator (IDataTemplate).

How can i achieve this?

**Comment by SKProCH** [comment]
Hello, @Maruhl 

In 5fe712b i replace `ContentControl` with `ContentPresenter` in custom dialogs. `ContentPresenter` allows to use ViewLocator which defined like this in your `App.xaml`:
```
<Application.DataTemplates>
    <local:ViewLocator/>
</Application.DataTemplates>
```

You can try in by installing [2.4.1.26-nightly](https://www.nuget.org/packages/Material.Avalonia/2.4.1.26-nightly) package version. 

Does this solve your problem?

**Comment by Maruhl** [comment]
Thanks for the fast reply. I tested my app with the 2.4.26-nightly package and it doesn't work.
After that, i forked this branch, to implement the custom dialog test - and it works.

But why not in my app? Mh, very strange, there is not special things. The app runs in .Net 6.0 - but i think that is not the problem. I'll have to see what the problem is.

**Comment by SKProCH** [comment]
@Maruhl 
> But why not in my app? Mh, very strange, there is not special things. The app runs in .Net 6.0 - but i think that is not the problem. I'll have to see what the problem is.

You should place breakpoint in `Build` method of your ViewLocator and see which values come to this method.  

Note: for default implementation of ViewLocator your view must be named properly: for example, for Avalonia.NETCoreMVVMApp.**ViewModel**s.MainWindow**ViewModel** view should be Avalonia.NETCoreMVVMApp.**View**s.MainWindow**View**

**Comment by Maruhl** [comment]
Yes i know, the whole app works with this behavior. I debug the Avalonia ContentPresenter, to find out why the ViewLocator not used. 
This is the normal Behavior:

![grafik](https://user-images.githubusercontent.com/41585619/141634923-3ad788e2-4d1b-4ce2-ba68-297d61b1818d.png)

But if i invoke the DialogProvider then is the result by "FindDataTemple" another thing:

![grafik](https://user-images.githubusercontent.com/41585619/141636612-6b307ce8-698a-4469-89a3-eadb11b6d562.png)

**Comment by Maruhl** [comment]
Mkay... my fail. ViewLocator is used, but i forgot to extend the Match-Method. OMG!
Sorry for the inconvenience, I can't see the forest for the trees.
