### ISSUE TITLE
Show password button is not visible until clicked

### ISSUE THREAD

**Issue by Al-Dyachkov** [AvaloniaCommunity/Material.Avalonia#124]
Issue is reproduced in material.demo

![image](https://user-images.githubusercontent.com/10960735/142627351-6a0a74d4-fcdf-4c91-9bf2-bb349bacf693.png)

**Comment by appleneko2001** [comment]
Sorry for taking a long times to fix issues!
The reveal password button should be usable for now, and it will be visible even the field is empty!

**Comment by Al-Dyachkov** [comment]
> Sorry for taking a long time to fix issue!
No problem. Thanks for maintaining the project.

Everything looks good now, closing the issue.
