### ISSUE TITLE
Progressbar Width not scaleable < 200px

### ISSUE THREAD

**Issue by dojo90** [AvaloniaCommunity/Material.Avalonia#125]
It seems that the default width of the `ProgressBar` is `200px`. I need to have it smaller than `200px` in my application, unfortunately this cannot be adjusted.

```xaml
<StackPanel Orientation="Vertical">
  <ProgressBar Margin="5" Value="50" MaxWidth="25"></ProgressBar>
  <ProgressBar Margin="5" Value="50" MaxWidth="50"></ProgressBar>
  <ProgressBar Margin="5" Value="50" Width="100"></ProgressBar>
  <ProgressBar Margin="5" Value="50" Width="200"></ProgressBar>
  <ProgressBar Margin="5" Value="50" Width="205"></ProgressBar>
</StackPanel>
```

![grafik](https://user-images.githubusercontent.com/17551597/143565739-0b2b6c7f-a0aa-4757-a3ed-5095e8284db7.png)

**Comment by SKProCH** [comment]
Seems like its not a bug, its just you color palette progress bars.

Here is gif with changing progressbar width and showing results it previewer (yes, previewer is kinda buggy, so when you dont see circular progress bars animation - so here previewer is freezed):
![ProgressBars](https://user-images.githubusercontent.com/29896317/143719722-72044f3b-75ef-4a4f-aaa6-31ea6dfc7242.gif)

**Comment by dojo90** [comment]
I found the problem and it seems to be due to the styles involved.

Here is my `App.axaml`:

```xaml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:hmi="clr-namespace:HMI"
             xmlns:theme="clr-namespace:HMI.Theme"
             x:Class="HMI.App">
  <Application.DataTemplates>
    <hmi:ViewLocator />
  </Application.DataTemplates>
  <Application.Styles>
    <!-- https://github.com/PieroCastillo/Aura.UI -->
    <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/BaseLight.xaml"/>
    <StyleInclude Source="avares://Aura.UI.FluentTheme/AuraUI.xaml"/>
    <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml"/>
    <StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>
    <!-- default avalonia DataGrid (https://docs.avaloniaui.net/docs/controls/datagrid) -->
    <StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Default.xaml"/>
    <!-- https://github.com/AvaloniaUtils/Material.Icons.Avalonia -->
    <StyleInclude Source="avares://Material.Icons.Avalonia/App.xaml" />
    <!-- https://github.com/AvaloniaCommunity/material.avalonia -->
    <StyleInclude Source="avares://Material.Avalonia/Material.Avalonia.Templates.xaml" />
    <!-- HtSuite -->
    <StyleInclude Source="avares://HtSuite.Avalonia.HMI/Infrastructure/Keyboard/VirtualKey.axaml" />
  </Application.Styles>
  <Application.Resources>
    <theme:HaprotecCorporateDesignTheme BaseTheme="Inherit" PrimaryColor="Grey" SecondaryColor="Orange" />
  </Application.Resources>
</Application>
```

As described in your README ... the original styles should be included beforehand:

![grafik](https://user-images.githubusercontent.com/17551597/143842917-dfb694e6-6256-4419-a37b-552285f012e1.png)

If I comment out the following line:
```xaml
<StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>
```

The `ProgressBar` works as expected:

![grafik](https://user-images.githubusercontent.com/17551597/143843082-2ffb0eba-af71-406a-8f18-92f81e7c48fc.png)

Isn't the style reliably overwritten here?

**Comment by appleneko2001** [comment]
Hi @dojo90 
Sorry for a long wait!
I found why it happens, and I have [uploaded the solution.](https://github.com/AvaloniaCommunity/Material.Avalonia/commit/ba39cad8e35dfa15594f4b178617d25df4a68fd1) You can get the fix from nightly source, if you need it early. 
ProgressBar have been fixed, but other controls are still affected by `Avalonia.Themes.Default` For example, ListBox had a padding, but it doesn't defined in our libs.
![image](https://user-images.githubusercontent.com/38249047/146942891-7eacf23a-023f-4355-8421-1d846119494b.png)
![image](https://user-images.githubusercontent.com/38249047/146942929-2c5473e3-5082-474a-9fd4-2eb19c3cb228.png)

**Comment by dojo90** [comment]
Thanks for your fix! 👍

I am pleased that the error was found and that it was not due to my project. Nevertheless, it is annoying that we have a fundamental incompatibility when inheriting styles (https://github.com/AvaloniaCommunity/Material.Avalonia/issues/132).
