### ISSUE TITLE
Material.Icons dll is so huge (5,7Mo)

### ISSUE THREAD

**Issue by flarive** [AvaloniaCommunity/Material.Avalonia#127]
Hi,

You're using a dependency to Material.Icons from this repo :
https://github.com/SKProCH/Material.Icons/

This external material icons lib by SKPoCH is great (thousands of icons) but in a end project we often use only a few icons.
In your Avalonia.Material you also only use a very few of them.

I try to reduce the size of the binaries of my .net 6 Avalonia app (size on the disk but also size in memory when the app is instanciated).

The Material.Icons.dll is so huge (5,7Mo for the 1.0.8 version and 6,5Mo for latest one).
If i comment all the icons I don't use in SKPoCH code, the dll is only 18Ko.

I try to replace the big dll with my reduced one i compiled myself but because of the deps.json file and the dependencies sha12 inside, i can't just switch the 5,7Mo Material.Icons.dll with my 18Ko one.
(The app don't lauch because of the bad sha12 in deps.json)

Would you have an idea on how to solve that ?
May be by removing this lib from your dependencies and by having just the few icons xaml you need in your resources file.

Memory footprit and green software is so important in 2021...

Thanks a lot

Eviral

**Comment by appleneko2001** [comment]
I created an Internal Icon view and integrated some icons to internal icons data set. All those changes are in [this commit](https://github.com/AvaloniaCommunity/Material.Avalonia/commit/d78e76fd24410f79fed5b9c174fe4c274afe652f).

Integration are almost complete, but there something are trying to block our way. Maybe this function is still used by other project that I cant tell, so [I set this function as obsoleted](https://github.com/AvaloniaCommunity/Material.Avalonia/commit/7e3ec2f920fa3d6103d22fbeba95aa19bf692c6f) and I want to remove it later. 

To use an alternative way of creating FABs in code-behind, [FloatingButtonBuilder](https://github.com/AvaloniaCommunity/Material.Avalonia/commit/43cddceed933bfe7141a5d559ad397ccd578560b) will be handy on this case. I will commit fixes, if I find any glitches of this builder.

**Comment by flarive** [comment]
Thanks a lot !
I'm going to try :)

**Comment by appleneko2001** [comment]
Hi @flarive
I have completed the integration of this. You can get update from nightly source. For now I just need update wiki (Add entry about `FloatingButtonBuilder`).

**Comment by flarive** [comment]
Hi @appleneko2001,

I have tried the latest nightly build 2.5.0.40 but i have an exception here :

![ex1](https://user-images.githubusercontent.com/7724904/147050018-211b632e-a1fc-4873-a065-d994414c52fb.png)

Here is my context :

![ex2](https://user-images.githubusercontent.com/7724904/147050093-af7b9788-bc16-47be-a1b8-687cb8afdb2c.png)
![ex3](https://user-images.githubusercontent.com/7724904/147050104-a13be456-6c9d-4e8b-9256-f760785b51ee.png)

Thanks for your help :)

**Comment by appleneko2001** [comment]
There I miss one. I have removed the `Material.Icons.Avalonia` reference in index file.
Update your nightly package to look changes for now.

**Comment by flarive** [comment]
Works very well now !
Thanks a lot

**Comment by SKProCH** [comment]
Fixed in `3.0.0-avalonia10-preview1`
