### ISSUE TITLE
May I open navigation drawer from right side ? (fixed issue title)

### ISSUE THREAD

**Issue by flarive** [AvaloniaCommunity/Material.Avalonia#131]
Hi guys,

I would like to open the Snackbar host side menu (such as in demo project) on the right side of the screen instead of the left.
Is it possible ?
I can't find any NavigationDrawer.RightDrawerContent, just NavigationDrawer.LeftDrawerContent...

Thanks a lot guys, i love material avalonia :)

**Comment by appleneko2001** [comment]
Sorry for a long waits! I was misunderstand the question about when I see this issue for now.
So there we have properties named `SnackbarHorizontalAlignment` and `SnackbarVerticalAlignment`. They used for change where snackbar should appear to.

You could just add tag `SnackbarHorizontalAlignment="Right"` for your case!

![image](https://user-images.githubusercontent.com/38249047/151659595-b2d70f50-e482-46ed-9c66-6e8e3f51c27b.png)

**Comment by flarive** [comment]
Hi,
Sorry i wasn't very clear... I made a confusion between snackbar and menu panel.
I'm was talking about the left side menu panel that appears when you click on the menu icon just before the Material.Avalonia Demo title on your previous screenshot.
I would like to be able to open the side menu at the right of the screen instead of the left.

**Comment by appleneko2001** [comment]
Hi flarive
I got ya! You want ask "May I open navigation drawer from right side?"
Of course you can! This feature is available after [commit#a4a2d8c8689ee072d507838e43da29b435f3f996](https://github.com/AvaloniaCommunity/Material.Avalonia/commit/a4a2d8c8689ee072d507838e43da29b435f3f996) (version of package is [2.5.0.70-nightly](https://www.nuget.org/packages/Material.Avalonia/2.5.0.70-nightly)). So you have to install Material.Avalonia version 2.5.0.70-nightly or newer.

The usage is same as previous how you did. Just use properties with prefix "Right" but not "Left". Pretty similar like MDIX library.

Example:
```xml
<styles:NavigationDrawer RightDrawerOpened="True">
	<styles:NavigationDrawer.RightDrawerContent>
		<TextBlock Text="Text from right drawer"/>
	</styles:NavigationDrawer.RightDrawerContent>
</styles:NavigationDrawer>
```
This one will open drawer with text "Text from right drawer" from right side.

**Comment by flarive** [comment]
Thanks man !
Let me test it and give you my feedback soon :)

**Comment by flarive** [comment]
Works perfectly ! Thanks !
