### ISSUE TITLE
Compatibility with Avalonia.Themes.Default

### ISSUE THREAD

**Issue by appleneko2001** [AvaloniaCommunity/Material.Avalonia#132]
I have found some compatibility issues with official theme `Avalonia.Themes.Default`

For example, we have [a issue from @dojo90 early](https://github.com/AvaloniaCommunity/Material.Avalonia/issues/125), about ProgressBar sizing issue, if your application using our styles with `Avalonia.Themes.Default`. I tried to fix this issue today, and waiting for feedback, but I found another issue that similar like this. The regular `Slider` control will completely hidden.

![image](https://user-images.githubusercontent.com/38249047/146944717-ef4aec82-a4e5-4dd6-8bf7-08227a67b561.png)

I think we need to find a complete solution for this situation. I know people not gonna use our styles only, and I can imagine what happen next.

**Comment by SKProCH** [comment]
Actually Material.Avalonia pretty compatible with Default theme (because we use default theme in demo app, actually). But with new Avalonia 11 themes feature this is become unactual, cuz themes eliminates the styles leaking problem
