### ISSUE TITLE
ProgressBar Classes not being found

### ISSUE THREAD

**Issue by MarioGK** [AvaloniaCommunity/Material.Avalonia#135]
Hi, i tried using the same code as the Demo app but the Progress Bar is not showing and working correctly, i tried using the latest stable and nightly builds

ProgressBar Code:

![image](https://user-images.githubusercontent.com/8379079/147507045-4fb0d29a-7b64-4b46-87d1-69f9b6a438e9.png)

App.xaml:

![image](https://user-images.githubusercontent.com/8379079/147507216-724bf8ed-b5b4-42a7-94e4-23aaf9f059de.png)

**Comment by SKProCH** [comment]
Hello, @MarioGK 

Can you provide this project (or minimum reproducible example)? We need this this to investigate the problem.

**Comment by appleneko2001** [comment]
Hi! @MarioGK 
In the past of half years we didnt received your glitch reproduce example, and there was a lot of changes of our library. You can try to reproduce it with 3.0.0-rc nightly package and send us feedback here! We might to close this issue by inactivity if we didnt receive your feedback within June 2022.
Thanks!
