### ISSUE TITLE
Icons missing upgrading to 2.5.0.44-nightly

### ISSUE THREAD

**Issue by ctrl-alt-d** [AvaloniaCommunity/Material.Avalonia#137]
After upgrade from 2.5.0.**43**-nightly **to** 2.5.0.**44**-nightly, icons are missing. What I'm doing wrong?

### Before upgrade (2.5.0.43-nightly):

<img width="1305" alt="screenshot with icons" src="https://user-images.githubusercontent.com/3105983/148651463-c9d9c04b-d941-4ec8-b302-bf0b24c1d8b7.png">

### After upgrade (2.5.0.44-nightly):

<img width="1287" alt="screenshot without icons" src="https://user-images.githubusercontent.com/3105983/148651473-8b471666-de32-4b05-bd10-61b786a95780.png">

References:

```xml
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.11" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.11" />
    <PackageReference Include="Avalonia.Diagnostics" Version="0.10.11" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.10.11" />
    <PackageReference Include="Material.Icons.Avalonia" Version="1.0.2" />
    <PackageReference Include="Material.Avalonia" Version="2.5.0.44-nightly" />
  </ItemGroup>
```

My repo: https://github.com/ctrl-alt-d/eaprecull/tree/main/UI.ER.AvaloniaUI

**Comment by appleneko2001** [comment]
Hi there!
For now you need add reference `Material.Icons.Avalonia` manually after [icons migration issue (issue #127)](https://github.com/AvaloniaCommunity/Material.Avalonia/issues/127).

```xml
<StyleInclude Source="avares://Material.Icons.Avalonia/App.xaml"/>
```

You can visit [Getting started of Material.Icons.Avalonia / Readme](https://github.com/AvaloniaUtils/Material.Icons.Avalonia/blob/master/README.md) if you want know more information about this package.

**Comment by ctrl-alt-d** [comment]
Wow. Like a charm! Running fine on 2.5.0.49-nightly. Thanks a lot @appleneko2001
