### ISSUE TITLE
TextBox.Filled.clearButton issue

### ISSUE THREAD

**Issue by CIRCULARKA** [AvaloniaCommunity/Material.Avalonia#144]
My code: ```<TextBox Classes="Filled clearButton">``` outputs the following after I input some text into control (dark theme):

![image](https://user-images.githubusercontent.com/34581740/149985973-3b1efb1a-40d9-4b1a-9dee-5fa0a0643d8d.png)

Why are there two crosses? Can you fix that? I really want to use this control now

**Comment by SKProCH** [comment]
Hello, @CIRCULARKA 

I can't reproduce this on latest nightly build. Try to install latest nightly build and check if issue still appears there or provide minimal reproduceable example please.

**Comment by CIRCULARKA** [comment]
Hi. Sorry for not giving more information but I already tried to reproduce the issue in a new project and figured out that it was my fault, I forgot to exclude some styles that was doing all this to me. Thanks for response!
