### ISSUE TITLE
How to design MaterialDesign.Sheets: side

### ISSUE THREAD

**Issue by dojo90** [AvaloniaCommunity/Material.Avalonia#145]
Hello,

I would like to implement the `MaterialDesign.Sheets: side` (https://material.io/components/sheets-side). Have you ever thought about the best way to implement this?

Thank you

**Comment by appleneko2001** [comment]
Hi! The side sheet feature is ready for use! For now it supports desktop variant, mobile is planned.
You can use it in nightly build now!

**Comment by dojo90** [comment]
Wow! That was fast! I had already started to implement a `SideSheet`, but to be honest I like your solution better.

What do you think about implementing a `Button` to close the SideSheet with an associated property `CanClose`?

The right SideSheet is my implementation with a `Button`.
![grafik](https://user-images.githubusercontent.com/17551597/150941540-c79235a9-219b-4e8e-96ee-cf7ac632d32f.png)

**Comment by appleneko2001** [comment]
Thanks for your reply!
I think you can just hide button if you want to implement a "permanent" standard sidesheet
Just bind the `IsVisible` property to `IsEnabled` property itself button

**Comment by dojo90** [comment]
Yes, that's what I meant. `CanClose` switches the button visible or not. Since it could be also possible that you do not want to close the side sheet. 
But when looking at the documentation (https://material.io/components/sheets-side), there is actually no case in the desktop variant where the button is hidden. Thus, according to the official definition, it should always be visible. But I still think it would be more practical if you could hide it or not.

**Comment by appleneko2001** [comment]
I think sidesheet that able to close is more better and practical too. Sometimes, this view is optional for use but not always. So you need keep it visible.

This is my opinion to answer this question, of course.
