### ISSUE TITLE
Set KeyboardNavigation.TabNavigation property to Continue on ItemsPresenter

### ISSUE THREAD

**Issue by dojo90** [AvaloniaCommunity/Material.Avalonia#146]
I just ran into the following problem (https://github.com/AvaloniaUI/Avalonia/issues/7406) and would like to have the following property set in the custom dialogs as well. Would it be possible to implement this accordingly?

```cs
<ItemsControl.Styles>
        <Style Selector="ItemsPresenter">
            <Setter Property="(KeyboardNavigation.TabNavigation)" Value="Continue" />
        </Style>
</ItemsControl.Styles>
```

- https://github.com/AvaloniaCommunity/Material.Avalonia/blob/bfed8aabd5e656be9fea57a4a1c3d4ffcaad7e5d/Material.Dialog/Views/CustomDialog.axaml#L70
- https://github.com/AvaloniaCommunity/Material.Avalonia/blob/bfed8aabd5e656be9fea57a4a1c3d4ffcaad7e5d/Material.Dialog/Views/AlertDialog.axaml#L72
- https://github.com/AvaloniaCommunity/Material.Avalonia/blob/bfed8aabd5e656be9fea57a4a1c3d4ffcaad7e5d/Material.Dialog/Views/DatePickerDialog.axaml#L60
- https://github.com/AvaloniaCommunity/Material.Avalonia/blob/bfed8aabd5e656be9fea57a4a1c3d4ffcaad7e5d/Material.Dialog/Views/TextFieldDialog.axaml#L102
- https://github.com/AvaloniaCommunity/Material.Avalonia/blob/bfed8aabd5e656be9fea57a4a1c3d4ffcaad7e5d/Material.Dialog/Views/TimePickerDialog.axaml#L168
-

**Comment by SKProCH** [comment]
Hello, @dojo90 

You can create PR, we will merge it. Or you can wait until we implement this ourselves.
