### ISSUE TITLE
Binding on LeftDrawerWidth hides all content/behavior of NavigationDrawer 

### ISSUE THREAD

**Issue by Tenjim** [AvaloniaCommunity/Material.Avalonia#151]
Hi guys, 

With your demo, I have tried to bind this property from NavigationDrawer, LeftDrawerWidth to actual Width from the window to display more content.

```
<styles:NavigationDrawer Name="LeftDrawer" LeftDrawerWidth="{Binding $parent[Window].Bounds.Width}"
                                 LeftDrawerOpened="{Binding ElementName=NavDrawerSwitch, Path=IsChecked, Mode=TwoWay}">
```

When I want to open that NavigationDrawer, the content is hidden on the left and when you enlarge the window's size, this control take the right width but we can't close anymore this NavigationDrawer.

Have you some clues about that ?
Without Binding and set a static LeftDrawerWidth, it's working but I need to adjust width depend on screen we have.

Thanks in advance.

**Comment by appleneko2001** [comment]
Hi Tenjim
Which Material.Avalonia version you are using now? Is the latest nightly version?
I submitted a lot changes on nightly branch and there was differences between previous stable library.

**Comment by Tenjim** [comment]
Hi @appleneko2001 

Thank for you answer, I was on the 2.5.0.45-nightly. I just updated and I'll keep you notice if it's resolved :)

**Comment by Tenjim** [comment]
Thanks, It's resolved on the latest version.

@appleneko2001 , how can we see release note on nightly version to see changes ?

**Comment by appleneko2001** [comment]
Hi Tenjim
I'm glad to see the problem was solved! This issue will be closed after next release.

The detail of changes will visible in [commits](https://github.com/AvaloniaCommunity/Material.Avalonia/commits/dev). We didn't wrote any release notes after publish. May I will try to write some release notes I think.

**Comment by Tenjim** [comment]
Hi  @appleneko2001,

Thanks and noted for commits :)
