### ISSUE TITLE
Custom dialog view not binding to vm

### ISSUE THREAD

**Issue by sabuto** [AvaloniaCommunity/Material.Avalonia#152]
Hi,

I am using version 2.5.0.71-nightly

So i have a custom view inheriteted from reactiveusercontrol with a textbox text value bound to Name

i have a viewmodel inherited from viewmodelbase with `[Reactive] public string Name { get; set; }` (I have foddy installed too)

and i create a new custom dialog like so:

```
NewObsConnectionViewModel vm = new NewObsConnectionViewModel();
            Window? window = LifetimeHelper.GetMainLifetime().MainWindow;
            DialogResult? result = awaitDialogHelper.CreateCustomDialog(new CustomDialogBuilderParams
{
                Borderless = true,
                ContentHeader = "test",
                Content = vm,
                DialogButtons = new[]
                {
                    new DialogResultButton { Content = "Add", Result = "ok" },
                    new DialogResultButton { Content = "Cancel", Result = "cancel" }
                }}).ShowDialog(window);
```

even if i new up the usercontrol and set that to the content and the datacontext to the vm i get the same results.

The Dialog actually shows up with the controls etc it just seems that the datacontext isnt being applied?

**Comment by appleneko2001** [comment]
Hi @sabuto !
This issue is related on my old coding-style and its so hard to fix. I'll post an issue about this later.

**Comment by appleneko2001** [comment]
Hi @sabuto ! I have a request for you.
Can you try the newest CustomDialog for us? I redesigned it since `2.5.0.76-nightly`. I added a property named ContentTemplate. It should be usable for your case. I need some feedback to improve this feature.
But be remember, I have cleaned the old code of TimePicker and DatePicker dialogs. So you have to downgrade to `2.5.0.73-nightly` after test if you are using those things in your project.

**Comment by sabuto** [comment]
I'll setup a new project and test :) will probably be tomorrow or Tuesday :)

**Comment by sabuto** [comment]
that works for me, awesome thanks

**Comment by appleneko2001** [comment]
Hi @sabuto ! Thanks for your contribution too🥳 That news was important for me.

Later we will release 3.0. There will have a API breaks on Theming feature and Dialogs. Styles will be changed by following standard of authoring controls (add root border (used for BorderBrush and BorderThickness property, with element name) and panel (allows more elements on root border, with element name) and etc.)
