### ISSUE TITLE
Add commit description to nightly packages changelog

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaCommunity/Material.Avalonia#153]
The detail of changes will visible in [commits](https://github.com/AvaloniaCommunity/Material.Avalonia/commits/dev). We didn't wrote any release notes after publish. May I will try to write some release notes I think.

_Originally posted by @appleneko2001 in https://github.com/AvaloniaCommunity/Material.Avalonia/issues/151#issuecomment-1025922770_

**Comment by SKProCH** [comment]
I think what i need to attach commit message as release notes for nightly packages to clearly see changes

**Comment by appleneko2001** [comment]
Could we use GitHub API to fetch commits of repository and create a base of release notes automatically? I still searching a way for archiving this.

**Comment by SKProCH** [comment]
@appleneko2001 Don't waste your time on this. I'll do it myself, it's easy enough.

**Comment by appleneko2001** [comment]
Ok then. Text me if you need ask somethin or any questions about this issue.

**Comment by SKProCH** [comment]
Done with latest buildscript changes
