### ISSUE TITLE
Modal dialog and background dark overlay

### ISSUE THREAD

**Issue by flarive** [AvaloniaCommunity/Material.Avalonia#155]
Hi guys,

When i open a modal dialog (window based), i would like the main window to be grayed with a dark black overlay.
Is it possible right now with Material Avalonia ?
Or is there a way to easily do that ?
It would be very cool to be able to customize the overlay color and opacity.

Here is screenshot showing that i'm talking about (taken from a WPF app).

![akXxW](https://user-images.githubusercontent.com/7724904/153367129-71d3e196-a00f-4ac0-b71b-ac0a8965d9e1.jpg)

Thanks a lot !

When do you plan to release Material Avalonia 2.6.0 built with Avalonia 0.10.12 ?

**Comment by SKProCH** [comment]
Hello, @flarive 

I think what you need to use DialogHost based overlays to achieve this. But if you need window based dialogs you can do it yourself - place something like `Rectanle` with `Opacity` and set `IsVisible` to `true` before opening dialog, and to `false` after closing dialog.

------
> When do you plan to release Material Avalonia 2.6.0 built with Avalonia 0.10.12?

As far as i know current (nightly) Material.Avalonia build is compatible with Avalonia 0.10.12. You can manually specify neverest Avalonia version in your csproj `PackageReference`s. If no - please open issue and we will fix that.

**Comment by SKProCH** [comment]
Does this solve your problem?

**Comment by flarive** [comment]
Yes, thanks !
I'm using window based dialogs (i didn't know you have made a DialogHost.Avalonia).
I just put a rectangle on my MainWindow with IsVisible property binded to a property of my main window view model, and it works like a charm !
Thanks a lot :)

May be you could add this behavior for window based dialogs in Material.Avalonia to avoid users to do that on their side.
It's just a suggestion :)

**Comment by SKProCH** [comment]
> May be you could add this behavior for window based dialogs in Material.Avalonia to avoid users to do that on their side.
May be in the future
