### ISSUE TITLE
TimePicker style missing

### ISSUE THREAD

**Issue by dojo90** [AvaloniaCommunity/Material.Avalonia#161]
Currently I do not see a style for the `TimePicker`. Has this been lost? `DatePicker` works without any problems at this point.

v2.5.0.73-nightly

**Comment by appleneko2001** [comment]
Hi! @dojo90 
I'm planning to update the dialog package. Please use older package, if you need TimePicker at this moment.
The new TimePicker and DatePicker style will be available in 3.0 stable release

**Comment by SKProCH** [comment]
TimePicker included in 3.0.0 package.
