### ISSUE TITLE
Link existing 'DialogHelper.IDialogWindow' logic with the 'DialogHost.Avalonia'

### ISSUE THREAD

**Issue by djonasdev** [AvaloniaCommunity/Material.Avalonia#164]
What is the best way to proceed if you want to link your existing `IDialogWindow` logic with the `DialogHost` (https://github.com/AvaloniaUtils/DialogHost.Avalonia)?

Currently I have implemented all popups or dialogs in my application with the `DialogHelper` class.

Since my application is designed as a desktop application and also as a "Kiosk app" on the Raspberry pi, I would like to find a solution how I can link my existing calls with the DialogHost.

**Comment by SKProCH** [comment]
@appleneko2001 can you take a look?

**Comment by appleneko2001** [comment]
Well I break the support because I moved templates to window styles
It should be marked as bug not enhancement
It was worked before

**Comment by SKProCH** [comment]
Apparently this is resolved now. Closing
