### ISSUE TITLE
How long will it take to develop the drawer function

### ISSUE THREAD

**Issue by OaimIsGnay** [AvaloniaCommunity/Material.Avalonia#169]
like this

<materialDesign:DrawerHost.Style>
                    <Style TargetType="materialDesign:DrawerHost" BasedOn="{StaticResource {x:Type materialDesign:DrawerHost}}">
                        <Style.Triggers>
                            <DataTrigger Binding="{Binding IsChecked, ElementName=BackgroundToggle}" Value="True">
                                <Setter Property="OverlayBackground" Value="{DynamicResource PrimaryHueMidBrush}" />
                            </DataTrigger>
                        </Style.Triggers>
                    </Style>
                </materialDesign:DrawerHost.Style>

materialDesign:DrawerHost.LeftDrawerContent

**Comment by SKProCH** [comment]
Hello, @OaimIsGnay 
If you mean DrawerHost from MaterialDesignInXaml, I think it's about a day or two of work. But my estimate may not be entirely accurate

**Comment by OaimIsGnay** [comment]
> 

Hi,Thank you for your reply.
I'm not in a hurry. I'm just asking if I have this idea.
