### ISSUE TITLE
Collapse navigation main page button not visible

### ISSUE THREAD

**Issue by ctrl-alt-d** [AvaloniaCommunity/Material.Avalonia#176]
After migrating to 3.0.0-rc0.92-nightly, the collapse navigation button is not visible. When the mouse is over, the button appears:

With cursor over button:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/3105983/177018838-810a5fe1-b4c9-4cb1-9584-0dbb6a53e332.png">

Without cursor over button:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/3105983/177018847-239c38c6-116f-40e0-b8fd-c786f0f5d688.png">

I have opened this issue trying to get help to fix it. I would like button was visible all time as before upgrading.

Here the code (almost the same of the sample):

https://github.com/ctrl-alt-d/eaprecull/blob/main/UI.ER.AvaloniaUI/Views/MainWindow.axaml

(To reproduce the issue, just clone repo and run)

Best regards and congrats about the quality of this repo!

**Comment by SKProCH** [comment]
Hello, @ctrl-alt-d 

Remove `ConstantForeground ImplicitForeground` classes from you ToggleButton

**Comment by ctrl-alt-d** [comment]
Hi @SKProCH ,

thanks!! Like a charm! <3
