### ISSUE TITLE
Custom controls time picker

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaCommunity/Material.Avalonia#18]
Need to add time picker as a custom control
![image](https://user-images.githubusercontent.com/33497292/68963650-7c73ea80-07e8-11ea-954b-6e0767f2c83d.png)

**Comment by appleneko2001** [comment]
TimePicker and DatePicker is on the way. TimePicker is almost ready.

**Comment by appleneko2001** [comment]
Both pickers are ready for use! DatePicker will appear in next update. 
Unfortunately, the DatePicker lacks on `Calendar` control, it works not like I expected. We need to remaster it in future updates. 

TimePicker
![](https://user-images.githubusercontent.com/38249047/117213592-c9ada700-ae36-11eb-8621-fb96af429aa0.png)

DatePicker
![](https://user-images.githubusercontent.com/38249047/117213662-dfbb6780-ae36-11eb-90cf-386f0c6ce8be.png)
