### ISSUE TITLE
Compatibility with Avalonia 11.0

### ISSUE THREAD

**Issue by Whiletru3** [AvaloniaCommunity/Material.Avalonia#180]
Hi,

Is there a plan to get a version compatible with Avalonia 11.0 Preview1 ?
I tried but I'm facing issues (like missing references of Avalonia.Layout).

Thanks

**Comment by SKProCH** [comment]
Hello, we are working on it

**Comment by SKProCH** [comment]
Hello, @Whiletru3 

I just published [3.0.0-avalonia11-preview2](https://www.nuget.org/packages/Material.Avalonia/3.0.0-avalonia11-preview2) version, you can give it a try.  
But we are not sure that all functions work properly, there may be bugs. If you find anything, open issue. 
We do not have enough time now to deal with the project, but we try to find it. PR is also warmly welcomed.

**Comment by SKProCH** [comment]
Also, here is another bug: #200

**Comment by SKProCH** [comment]
Seems like current version `3.0.0-avalonia11-preview3` should be fine with Avalonia 11, so i close this issue.
