### ISSUE TITLE
CreateCustomDialog Result

### ISSUE THREAD

**Issue by EricZeiberg** [AvaloniaCommunity/Material.Avalonia#190]
Is there a way to close and return a result from a `UserControl` object that is being opened via `DialogHelper.CreateCustomDialog()`? I don't see any documentation on this

**Comment by SKProCH** [comment]
@appleneko2001 can you help?

**Comment by appleneko2001** [comment]
Hi @EricZeiberg !
You can get your own result from your view model that provided while in dialog creation.
The custom dialog will return clicked button result string only. It means the dialog is just a wrapper to let your own control living in a window with dialog behaviours.
For example:
```csharp
///...
var myViewModel = new MyViewModel();
var myControl = new MyUserControl(){
    DataContext = myViewModel 
};
var dialog = DialogHelper.CreateCustomDialog(new (){
    Content = myControl,
    BialogButtons = DialogHelper.CreateSimpleDialogButtons(DialogButtonsEnum.OkCancel) 
};
var result = await dialog.ShowDialog(window);
var customResult = myViewModel.Result;
```
another way: Use your own `DataTemplate` resource that uses your view model and pass them in `CreateCustomDialog()` parameters.
```csharp
///...
Resources.TryGetResource("MyDialogDataTemplate", out var template);
var myDataTemplate = template as IDataTemplate;
var myViewModel = new MyViewModel();

var dialog = DialogHelper.CreateCustomDialog(new (){
    Content = myControl,
    ContentTemplate = myDataTemplate,
    BialogButtons = DialogHelper.CreateSimpleDialogButtons(DialogButtonsEnum.OkCancel) 
};
var result = await dialog.ShowDialog(window);
var customResult = myViewModel.Result;
```

PS: my code skill are awful and I created such thing that I dont like too(((
But I have found better design as like [MVVM-Dialogs](https://github.com/FantasticFiasco/mvvm-dialogs). Unfortunately I know it works only with WPF, avaloniaUI might not supported, the difficulty to adaption is unknown too. 
I might have free time to rework those things in November.

**Comment by EricZeiberg** [comment]
Is there not a way to pass my own data back from the custom dialog to the main window?

**Comment by appleneko2001** [comment]
well at this moment you can get your own results through your view model only
I doubt the answer is no if you ask (
but I dont sure how long those ways will be on there, everything might be changed over and over time.
I might change those crap if the new way and designs was the good approach to make it better.
