### ISSUE TITLE
FloatingButton Rendering errors

### ISSUE THREAD

**Issue by ApaulMyLittleAirport** [AvaloniaCommunity/Material.Avalonia#193]
![image](https://user-images.githubusercontent.com/45100828/202404983-b731f966-2ebf-4c02-957d-ad1d8e02c723.png)
3.0.0-avalonia11-preview2.121-nightly
11.0.0-preview4
When the mouse is moved over the button, a translucent right Angle appears

**Comment by SKProCH** [comment]
Hello, @ApaulMyLittleAirport 

Seems like this is an Avalonia bug (https://t.me/Avalonia/43002) and be fixed in a new avalonia preview
You can fix it by disabling Compositor in your Program.cs:
```csharp
// Here is your platform options \/
.With(new Win32PlatformOptions
{
    UseCompositor = false
})
```

Or you can manually override the style to fix it:
```
<Style Selector="controls|FloatingButton /template/ Border#PART_HoverIndicator">
     <Setter Property="CornerRadius" Value="{StaticResource FloatingButtonRoundCorner}"/>
</Style>
```

**Comment by ApaulMyLittleAirport** [comment]
Thank you very much for taking time out of your busy schedule to answer my questions! Very useful!
