### ISSUE TITLE
The theme doesn't change

### ISSUE THREAD

**Issue by kilinnik** [AvaloniaCommunity/Material.Avalonia#197]
In the avalonia web app, the theme does not change to light when it is set in the styles in app.axml
[Webtest.zip](https://github.com/AvaloniaCommunity/Material.Avalonia/files/10133045/Webtest.zip)

**Comment by SKProCH** [comment]
Without Material.Avalonia styles everything remains the same.  
Seems like this is an css issue, you need to look for `Background` and remove it from ccs files
