### ISSUE TITLE
Chinese symbols not rendered inside TextBox

### ISSUE THREAD

**Issue by yu35944570** [AvaloniaCommunity/Material.Avalonia#198]
Why inputFiled not support  chinese?

https://user-images.githubusercontent.com/50814599/205203544-6a904520-a30b-49f7-a657-080bb821aab4.mp4

**Comment by SKProCH** [comment]
Hello. Does Avalonia support the same Chinese characters by itself? As I can see the  upper textbox contains Chinese characters and everything is fine.

**Comment by yu35944570** [comment]
> Hello. Does Avalonia support the same Chinese characters by itself? As I can see the upper textbox contains Chinese characters and everything is fine.

**Comment by yu35944570** [comment]
here is my test ,the fisrt one successed, but the second and thrid failed ,if use my own  font,how do i set fontfamily‘s properties?
![1670026241308](https://user-images.githubusercontent.com/50814599/205411625-90b4bd6c-bce2-4a5a-822f-ce72aab23048.png)

**Comment by SKProCH** [comment]
You need to overwrite property `FontFamily` for `TextBlock` and `TextBox` (or, in your case may be in TextBox only). Put something like that in end of your App.Styles:
```
        <Style Selector="TextBox">
          <Setter Property="FontFamily">
            <FontFamily>Comic Sans MS</FontFamily>
          </Setter>
        </Style>
        <Style Selector="TextBlock">
          <Setter Property="FontFamily">
            <FontFamily>Comic Sans MS</FontFamily>
          </Setter>
        </Style>
```

**Comment by SKProCH** [comment]
Closing it as completed. If you still have questions - feel free to reopen this issue or create a new one
