### ISSUE TITLE
Runtime theme changing problems on Avalonia 11

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaCommunity/Material.Avalonia#200]
If you install `3.0.0-preview*` version and setup theme changing at runtime you can get troubles with, for example, TextBox colors (and left side bar in our demo):
![b658ae27-15d2-46e0-a29b-e6ed98065b01](https://user-images.githubusercontent.com/29896317/205518357-5b2d6b0e-273f-4b8e-a74c-b8910005b48b.gif)

This is known error and i don't know how to fix it. I think what that is something at Avalonia's side.
I figured out some workarounds:
1. You can set `UseCompositor = false` and `UseDeferredRendering = false` at your `BuildAvaloniaApp` method:
    ![image](https://user-images.githubusercontent.com/29896317/205518456-275281b6-0307-4135-a179-c327ce92b8a5.png)
    Make sure what you creating proper *PLATFORM*Options, where *PLATFORM* is your platform actually.
2. You can use `InvalidateVisual` at root element of scene (or at elements what incorrectly painted). After that you should trigger actual repainting of everything - for example, change window size

Also, **i need your help** to find out exactly what causes this behavior, create a minimal representative example, and help the Avalonia developers fix it (or fix it on our end, but I have no idea). All ideas, PR, examples and other warmly welcomed.

**Comment by appleneko2001** [comment]
I thought UseDeferredRendering wont affect this.
might we need research our theme applying procedure(((
I can try to addressing the reason of this glitch and fix workaround(if possible)

**Comment by appleneko2001** [comment]
Wait if `InvalidateVisual` helps then it means procedure cannot notify avalonia that resources has changed
use `Dispatcher` invoking notify changes workaround?

**Comment by SKProCH** [comment]
Interesting fact: if we replace `<TextBlock Classes="Body2" Text="Home" />` in ListBox in demo's MainWindow with just `Home` text - it will be change colors fine.

Here is gif:
![335db45d-4af2-485a-ba0c-672866514e21](https://user-images.githubusercontent.com/29896317/206926749-72081d90-50e4-4fa2-9632-bdaab2509eca.gif)
```
<ListBox Classes="NoScroll" Name="DrawerList"
         Focusable="{Binding ElementName=LeftDrawer, Path=LeftDrawerOpened}">
  <TextBlock>Home</TextBlock>
    Home
    Buttons
    ...
```

**Comment by SKProCH** [comment]
Seems like, if we reset theme at runtime, all controls start working fine.

Step by step:
1. Controls (TextBlock, TextBox) doesn't react to theme changing
2. Remove MaterialTheme from App.Styles completely
3. Add back MaterialTheme to App.Styles
4. Control are reacting to theme changes fine now
But this is doesn't work for controls which created after theme reattaching. (for example, we have buggy controls at Home tab, do reattach, buggy controls fixed, after that we switch to Fields (TextBox'es) tab, everything doesn't work property for textboxes)

**Comment by SKProCH** [comment]
Seems like i figured out it in more details

**Comment by SKProCH** [comment]
Fixed with Avalonia 11 preview 5.
