### ISSUE TITLE
Some items don't work.

### ISSUE THREAD

**Issue by DarlingInSteam** [AvaloniaCommunity/Material.Avalonia#201]
Hello. I had a problem that when avalonia.material was included, some buttons in the application stopped working. How can I fix this problem. I am using the latest version of avalonia and the latest version of avalonia.material.

App.Axamal

`<Application
    x:Class="SchoolTimetabler.App"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:themes="clr-namespace:Material.Styles.Themes;assembly=Material.Styles"
    xmlns:local="using:SchoolTimetabler">

    
    
    

    <Application.Styles>
        <themes:MaterialTheme BaseTheme="Light"
                              PrimaryColor="Purple"
                              SecondaryColor="Indigo" />
        <StyleInclude Source="avares://Material.Icons.Avalonia/App.xaml" />
        <StyleInclude Source="avares://Material.DataGrid/DataGrid.xaml" />
        <StyleInclude Source="avares://DialogHost.Avalonia/Styles.xaml" />
    </Application.Styles>
</Application>
`

**Comment by DarlingInSteam** [comment]
I checked my basic code with simple themes and fluent themes. Everything works. 
If you want to see the original project, it is called school_timetabler on my git hub.

**Comment by SKProCH** [comment]
@DarlingInSteam 
I've made a fix, does this solve your problem?

**Comment by DarlingInSteam** [comment]
Yup! Fix helped. Thank you.
