### ISSUE TITLE
Any chance of compatibility with cibuild?

### ISSUE THREAD

**Issue by MrakDev** [AvaloniaCommunity/Material.Avalonia#202]
There's any chance of compatibility with cibuild/nightly?

**Comment by MrakDev** [comment]
Avalonia 11.0.999-cibuild******-beta from [https://nuget.avaloniaui.net/repository/avalonia-all/index.json](https://nuget.avaloniaui.net/repository/avalonia-all/index.json) which is compatible with nativeaot. but I kinda found a way to.

**Comment by SKProCH** [comment]
Oh, I'm glad to hear that. It would be great if you could describe the way, maybe someone else will need it, @MrakDev
