### ISSUE TITLE
Edit Tabcontrol Style Failed

### ISSUE THREAD

**Issue by yu35944570** [AvaloniaCommunity/Material.Avalonia#203]
I edit Tabcontrol‘s assists:TabControlAssist.TabHeaderHorizontalAlignment =left ,but tabheader is still in middle?

**Comment by yu35944570** [comment]
![1671067398295](https://user-images.githubusercontent.com/50814599/207750338-d5cc1e8f-a17a-46d4-9233-da16bf33d484.png)

**Comment by SKProCH** [comment]
Should be fixed in last nightly. Please, try it and verify what this is fixed.
