### ISSUE TITLE
не отображается скролл хелпер в ветке 3.0

### ISSUE THREAD

**Issue by ecvento** [AvaloniaCommunity/Material.Avalonia#206]
![image](https://user-images.githubusercontent.com/110647032/212218462-9fff89fd-2f8c-4b9e-baae-2141dcf07210.png)

Демо версии 2.5

![image](https://user-images.githubusercontent.com/110647032/212218632-0cd2bdfa-d3c1-4e50-92fa-9a8f46313db2.png)

Версия 3.0 (ветка майор)

**Comment by SKProCH** [comment]
Должно быть исправлено в последнем nightly релизе
