### ISSUE TITLE
Thin Slider "material-v1" not working for 3.0 nightly

### ISSUE THREAD

**Issue by Mrxx99** [AvaloniaCommunity/Material.Avalonia#207]
The thin sliders "material-v1" don't work / are invisible with the latest nightly and the latest commit on the 3.0 branch.
Can also be observed on the Demo app.

Would it maybe also make sense to call them thin slider instead of v1? that better transports the meaning

**Comment by SKProCH** [comment]
Seems like a theme for them available as `MaterialSliderV1`, but there is still nothing rendered.  
Did you actually need them back, @Mrxx99? They are considered "deprecated", but if someone still need exactly this style, i can try to resurrect them

**Comment by Mrxx99** [comment]
Yes, it would be valuable to keep them I think. Sometimes the default one is just to big.
Currently wanting to use it in an app where it worked with older version

**Comment by SKProCH** [comment]
Ok, I'll try to restore it as theme. Now use still can use it as a old plain "styles" variant. 

Include styles:
```xaml
<StyleInclude Source="avares://Material.Styles/Slider.xaml" />
```

And after that you can use it as in `2.*` version
