### ISSUE TITLE
Cannot set FontSize on Material UI controls

### ISSUE THREAD

**Issue by henrydunphy** [AvaloniaCommunity/Material.Avalonia#208]
I asked the question to the [Avalonia Git Repo](https://github.com/AvaloniaUI/Avalonia/issues/9706), but looks like its an issue with Material.Avalonia. I cannot use the FontSize property on TextBox or Buttons. 
When setting TextBox Fontsize property nothing happens. I have tried both through code and the xaml side with no effect. This appears to be a bug on most controls including buttons. Luckily for buttons I have a work around. The workaround for buttons doesn't work on TextBox I'm guessing because it doesn't have the same hierarchy.

Attempts:
XAML file
`<TextBox Name="UserInputTextBox" FontSize="35" />`

code behind (using reactive UI):
```
public partial class LoginView : ReactiveUserControl<LoginViewModel>
{
    private ListBox _userNameListBox => this.FindControl<ListBox>("UserNameListBox");
    private TextBox _userInputTextBox => this.FindControl<TextBox>("UserInputTextBox");


    public LoginView()
    {
        InitializeComponent();

        this.WhenActivated(disposables => {
            this.Bind(ViewModel, vm => vm.UserInput, v => v._userInputTextBox.Text).DisposeWith(disposables);
            this.OneWayBind(ViewModel, vm => vm.SubmitEnabled, v => v._userInputTextBox.IsEnabled).DisposeWith(disposables);

            _userInputTextBox.FontSize = 35;
        });
    }
}
```

Button workaround:
```
		<Style Selector=".LoginButton > TextBlock">
			<Setter Property="FontSize" Value="35" />
			<Setter Property="Foreground" Value="White" />
		</Style>
```

**Comment by SKProCH** [comment]
Hello, @henrydunphy 

I've fixed it in last nightly release. Can you take a look?
