### ISSUE TITLE
DialogHost dialog enhancements

### ISSUE THREAD

**Issue by Coolkeke** [AvaloniaCommunity/Material.Avalonia#212]
Have you ever thought about enhancing the dialog function？
For example, the dialog box supports multiple pop-ups. At present, the dialog box only supports one pop up. When a new dialog box needs to pop up, the previous dialog box must be closed to open a new dialog box.
I'm not talking about Messagebox for AvaloniaUI, but DialogHost.
In response to the above requirements, I have written an enhanced version of DialogHost myself. If you don't mind, you can go to see the dialog function in one of my projects. I'm not promoting my project here. I only modified it by referring to your dialog box. Thank you for providing me with ideas. My project address is [https://github.com/Coolkeke/LayUI-Avalonia](https://github.com/Coolkeke/LayUI-Avalonia) @danwalmsley

**Comment by SKProCH** [comment]
Hello, did you talking about Dialogs in Material.Avalonia or about [DialogHost.Avalonia](https://github.com/AvaloniaUtils/DialogHost.Avalonia) features?

If it about DialogHost.Avalonia, i thinking about enchancing them, but i do not so much free time to do that, and, actually do not know how to implement multiple popups in proper way (I know how to do it, but I don't know how to make it friendly usable)

**Comment by Coolkeke** [comment]
Thank you for your reply. I'm here to provide you with the actual requirements of DialogHost. Because DialogHost.Avaloaia is only a relatively simple dialog function at present. In the development process, there are more dialog pop-up requirements, so I give you the following suggestions

**Comment by SKProCH** [comment]
So, i think what you should open issue in DialogHost repository actually
