### ISSUE TITLE
Preview version 5 cannot work!

### ISSUE THREAD

**Issue by wj8400684** [AvaloniaCommunity/Material.Avalonia#215]
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/39239954/219279124-940ffe8f-7177-415e-932d-a57dffc2348e.png">

**Comment by SKProCH** [comment]
Yep, preview 5 still WIP

**Comment by wj8400684** [comment]
When is it expected to be repaired?

**Comment by SKProCH** [comment]
I try to do this in this week

**Comment by SKProCH** [comment]
Should be fixed in nightly release `3.0.0-avalonia11-preview3.145-nightly`. But there is still bugs, at least in demo project

**Comment by SKProCH** [comment]
Issue with current preview-5 todo list: https://github.com/AvaloniaCommunity/Material.Avalonia/issues/215
