### ISSUE TITLE
ContextMenu displays abnormally

### ISSUE THREAD

**Issue by Zhou-Pixel** [AvaloniaCommunity/Material.Avalonia#219]
![截屏2023-04-10 09 28 07](https://user-images.githubusercontent.com/72525794/230807873-e3d5f350-a446-45ab-b641-28c833a88293.png)

`Avalonia Version="11.0.0-preview5" `
`Material.Avalonia Version="3.0.0-avalonia11-preview3.148-nightly" `

**Comment by SKProCH** [comment]
Hello, @Zhou-Pixel 
Can you try the latest nightly: https://www.nuget.org/packages/Material.Avalonia/3.0.0-avalonia11-preview3.152-nightly ?

**Comment by Zhou-Pixel** [comment]
> Hello, @Zhou-Pixel Can you try the latest nightly: https://www.nuget.org/packages/Material.Avalonia/3.0.0-avalonia11-preview3.152-nightly ?

![image](https://user-images.githubusercontent.com/72525794/231143300-97f1bf37-c1b2-48f5-ad28-f632a101dc7b.png)

It still has some problems on Windows, when using latest Avalonia and Material.Avalonia

**Comment by SKProCH** [comment]
Hello, @Zhou-Pixel 

Should be fixed in last nightly

**Comment by Zhou-Pixel** [comment]
> Should be fixed in last nightly

Thanks, it looks good

**Comment by SKProCH** [comment]
Closed as fixed in https://github.com/AvaloniaCommunity/Material.Avalonia/releases/tag/3.0.0-avalonia11-preview4
