### ISSUE TITLE
 Unable to resolve type Card from namespace clr-namespace:Material.Styles.Th emes;assembly=Material.Styles

### ISSUE THREAD

**Issue by Wael1231** [AvaloniaCommunity/Material.Avalonia#220]
hey gusy when i update old project avalonia 0.10.0 to 11.0.0preview6 i get this error :  Unable to resolve type Card from namespace clr-namespace:Material.Styles.Th
emes;assembly=Material.Styles 

can somone help me please

**Comment by SKProCH** [comment]
Hello, @Wael1231 

You probably should check what you install correct versions of packages and check the namespace of `Card` control. Also, you can try to reference `Card` control in your C# code and your IDE should suggest you a right namespace for it. If it can't suggest anything, you probably do not reference nuget package properly.

**Comment by SKProCH** [comment]
Also, i recommend to use the last nightly package for `11.0.0preview6`.

**Comment by SKProCH** [comment]
Current namespace is `Material.Styles.Controls` actually. You can try to change it and see, if it fixes the problem. Also, you can try Jetbrains Rider as it can suggest appropriate namespace for controls in axaml files.
