### ISSUE TITLE
Updating Material.Avalonia

### ISSUE THREAD

**Issue by Wael1231** [AvaloniaCommunity/Material.Avalonia#221]
what is equivalent of this xmlns:styles="clr-namespace:Material.Styles;assembly=Material.Styles"
The error : Unable to resolve type Card from namespace "clr-namespace:Material.Styles;assembly=Material.Styles"

how i can fix it please in  Avalonia 11.0.0preview6 ? and thanks

**Comment by SKProCH** [comment]
Closing it as duplicated in #220
