### ISSUE TITLE
How can i use this on a particular UserControl alone

### ISSUE THREAD

**Issue by Eugenenoble2005** [AvaloniaCommunity/Material.Avalonia#224]
The below doesent work and throws an exception that some resources are missing:
`	<UserControl.Styles>
		    <StyleInclude Source="avares://Material.Avalonia/Material.Avalonia.Templates.xaml" />
	</UserControl.Styles>
	<UserControl.Resources>
		<material:BundledTheme BaseTheme="Light" PrimaryColor="Teal" SecondaryColor="Amber"/>
	</UserControl.Resources>`

**Comment by SKProCH** [comment]
Hello, @Eugenenoble2005 

Can you provide a exception?

**Comment by SKProCH** [comment]
Closing this issue as staled. Feel free to reopen it or create a new one if the problem persists or you have any questions.
