### ISSUE TITLE
How to completely change the background color of pop-up windows？

### ISSUE THREAD

**Issue by 867824092** [AvaloniaCommunity/Material.Avalonia#226]
SDK version ： Avalonia 0.10.19,  DailogHost.Avalonia  0.6.0-avalonia10,  Material.Avalonia  3.0.0-avalonia10-preview2.126-nightly

Hello, I have set dialogHostAvalonia: DialogHost in MainWindow, as shown in the following figure。
![image](https://user-images.githubusercontent.com/49057777/236670113-c8a9e176-b408-4ffa-b159-5ad3e1eaf44b.png)
Then I created a UserControl to display the content of the pop-up window, as shown in the following figure。
![image](https://user-images.githubusercontent.com/49057777/236670174-dfa931e7-3bd5-4dba-becd-b4f8fbca61f1.png)
How to set the white border background color in the image below to transparent when I click the button to pop up the form。
![image](https://user-images.githubusercontent.com/49057777/236670309-0897d0a8-dfc4-4a5f-8fe4-3f5ee458e764.png)

**Comment by SKProCH** [comment]
Hello, @867824092 

You can set `Background` property of `DialogHost`.
But i think you shouldn't define background in your user control, better use Background property of DialogHost.

**Comment by 867824092** [comment]
> You can change it via property of . But i think you shouldn't define background in your user control, better use Background property of DialogHost.`Background``DialogHost`

Hello, @SKProCH 

I have set the Background property of DialogHost, but it has not taken effect。
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/49057777/d74522ad-8c84-453b-818b-c6e8c15eafb7)

![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/49057777/7312eeb4-19f0-461c-9437-b48769f92421)

**Comment by SKProCH** [comment]
Which version of Avalonia, DialogHost and Material.Avalonia you are using?

For me at latest Material.Avalonia code in 3.0 branch everything works:
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/29896317/29466e6d-5400-41f7-94fe-39afd105f47a)
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/29896317/710e7a86-f142-4fbe-a9b4-48fd9f9685c9)

**Comment by 867824092** [comment]
SDK Version:  Avalonia 0.10.19, DailogHost.Avalonia 0.6.0-avalonia10, Material.Avalonia 3.0.0-avalonia10-preview2.126-nightly.
Due to some reasons, Avalonia 11 preview version was not used.

![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/49057777/ffc32dbb-0e64-481b-a0fe-d4eeadc63c00)
