### ISSUE TITLE
DialogHost failed to open

### ISSUE THREAD

**Issue by wj8400684** [AvaloniaCommunity/Material.Avalonia#230]
<img width="1193" alt="image" src="https://github.com/AvaloniaCommunity/Material.Avalonia/assets/39239954/54dafb8e-6ec7-4448-8813-6124e76a1bfb">
<img width="1352" alt="image" src="https://github.com/AvaloniaCommunity/Material.Avalonia/assets/39239954/a3e6bbe5-527f-4b4d-be19-5928e03692de">
in preview 8.

**Comment by SKProCH** [comment]
Yep, thanks. Actually DialogHost was removed from demo due to merging dev to 3.0 branch... This is strange. Now it's back.
