### ISSUE TITLE
Implement styles for WindowNotificationManager and NotificationCard

### ISSUE THREAD

**Issue by wj8400684** [AvaloniaCommunity/Material.Avalonia#231]
<img width="1193" alt="image" src="https://github.com/AvaloniaCommunity/Material.Avalonia/assets/39239954/a50b6ef6-f984-4ceb-a452-5806b3af5a91">
<img width="527" alt="image" src="https://github.com/AvaloniaCommunity/Material.Avalonia/assets/39239954/ba2cce89-1caa-4a70-849b-8d6ff8276b09">

**Comment by SKProCH** [comment]
Hello, @wj8400684 

Can you provide a bit more information? 
In last build it works for me:  
![e93d2c29-ab3f-4493-8a14-4a843e614ad1](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/29896317/fcc9a85e-530a-4aee-aa9b-637c25bda55e)

**Comment by wj8400684** [comment]
I use WindowNotificationManager controls。

**Comment by wj8400684** [comment]
Can fix this?

**Comment by SKProCH** [comment]
> Can fix this?

Yep, try to implement that.

**Comment by SKProCH** [comment]
Oh, that's actually pretty easy to fix. But i need to rewrite styles to ControlTheme anyway.  
You can [install and use](https://github.com/AvaloniaCommunity/Material.Avalonia/wiki/Using-nightly-build-feed) latest nightly version [nuget](https://github.com/AvaloniaCommunity/Material.Avalonia/packages/572265) or wait until stable version of package has been released on Nuget feed.
