### ISSUE TITLE
3.0_major_update don't work in native AOT mode

### ISSUE THREAD

**Issue by flarive** [AvaloniaCommunity/Material.Avalonia#232]
Hello,

I have tried your great 3.0_major_update branch working with latest Avalonia 11 preview (8).
I would like to ve able to compile the demo project in Native AOT mode to reduce size and memory footprint.
I'm targeting .net7.

In the demo csproj i have added :
```
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
```

When i run a dotnet publish -c release, the compilation works to the end but i have trimming warnings.

When i try to execute the native AOT binary (much smaller than without native AOT), nothing happened, the exe can't start.

It would be so cool if Material Avalonia could work with Native AOT !

Thanks a lot !

Eviral

**Comment by SKProCH** [comment]
Hello, @flarive 

I think this is a complicated thing actually. I'll try to look at what I can do. Also, any support is highly appreciated.

**Comment by flarive** [comment]
Yes, I know it's not easy...
I have looked into the Windows Event viewer to get info why the app crash in native AOT but it doesn't help much.

This avalonia 11 exemple is working well when compiled in native AOT mode :
https://github.com/teobugslayer/AvaloniaCoreRTDemo

**Comment by SKProCH** [comment]
I think what first step is enable compiled bindings for Material.Avalonia

**Comment by SKProCH** [comment]
Should be fine now as corresponding PR are merged.
