### ISSUE TITLE
Migrate styles to ControlThemes

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaCommunity/Material.Avalonia#233]
Before full `3.0.0` release we need to migrate all remaining Styles to ControlThemes.  
There is no much more left:

- [x] RepeatButton.xaml
- [x] AutoCompleteBox.xaml
- [x] CalendarButton.xaml
- [x] CalendarDayButton.xaml
- [x] CalendarItem.xaml
- [x] Carousel.xaml
- [x] ComboBox.xaml
- [x] ComboBoxItem.xaml
- [x] ContentControl.xaml
- [x] ContentExpandControl.axaml
- [x] ContextMenu.xaml
- [x] EmbeddableControlRoot.xaml
- [x] FlyoutPresenter.axaml
- [x] GridSplitter.xaml
- [x] Menu.xaml
- [x] MenuItem.xaml
- [x] NativeMenuBar.xaml
- [x] NotificationCard.xaml
- [x] NumericUpDown.xaml
- [x] OverlayPopupHost.xaml
- [x] PopupRoot.xaml
- [x] Separator.xaml
- [x] SplitView.xaml
- [x] ToolTip.xaml
- [x] WindowNotificationManager.xaml
- [x] SideSheet.xaml
- [x] TransitioningContentControl.axaml
- [x] Calendar.xaml

New files should be created in `Resources/Themes` folder and imported in `MaterialToolKit.xaml`.
All PRs and support are highly appreciated.

**Comment by SKProCH** [comment]
Some of the styles implemented via https://github.com/AvaloniaCommunity/Material.Avalonia/pull/239  
Thanks, @JanTamis

**Comment by JanTamis** [comment]
@SKProCH so the combobox doesnt work in the new preview. is this because it is not yet migrated to a controltheme?

**Comment by SKProCH** [comment]
Hello, @JanTamis 
No, seems like this is a bug. Can you raise an issue, please?

**Comment by JanTamis** [comment]
yes
