### ISSUE TITLE
Close left NavigationDrawer at startup

### ISSUE THREAD

**Issue by flarive** [AvaloniaCommunity/Material.Avalonia#237]
Hello,

I'm using 3.0_major_update branch and i would like the left navigation drawer to be closed at startup when i launch the app.
I can't find any easy way to do that, could you help me please ?

Thanks a lot

Eviral

**Comment by SKProCH** [comment]
Hello, @flarive 

Probably you need to set `LeftDrawerExpandThresholdWidth` to a value, bigger when you app width.

**Comment by Whiletru3** [comment]
Hi @SKProCH ,
I don't understand why the default value to 1000 ?
If the app start and is maximized, the LeftDrawer open itself without manual trigger

**Comment by SKProCH** [comment]
Hello, @Whiletru3  
Why not 1000?  
You can change it to whatever you want actually. Just put the bigger number and you don't get it open itself.

**Comment by jcummings2** [comment]
> > Then with LeftDrawerExpandThresholdWidth="9999"
> 
> To be clear, this is not a bug. This is overlay mode for "mobile like" GUIs, when you have less space than needed.
> 
> I've re-readed the conversation, and do I propertly get the point - you want to have ability to startup with closed drawer regardless of `LeftDrawerExpandThresholdWidth`?

Yes, I want the ability to have the drawer closed at startup. I only set `LeftDrawerExpandThresholdWidth` because that was the solution suggested here. As mentioned, I would expect the drawer to be closed whenever `LeftDrawerOpened` is set to `false` including at startup.

**Comment by SKProCH** [comment]
Changed behavior for LeftDrawerExpandThresholdWidth/RightDrawerExpandThresholdWidth == null.

The old one:

If set - check the width, if less make overlay mode, if more make expanded mode
If not set - make overlay mode
The new one:

If set - check the width, if less make overlay mode, if more make expanded mode
If not set - make **expanded mode**
(if user wants overlay mode at all time - he can just set double.MaxValue of something like that to that property)
