### ISSUE TITLE
Change the theme did not work properly

### ISSUE THREAD

**Issue by mfkwgizhoujian** [AvaloniaCommunity/Material.Avalonia#240]
Avalonia Version: 11.0.0-rc1.1
Material.Avalonia Version: 3.0.0-avalonia11-preview4.179-nightly
Demo Branch: avalonia-11-rc1

Run the project, change the theme to dark, the page did not switch to the dark theme, when I click the menu icon or menu item, the theme will change normally.

**Comment by SKProCH** [comment]
Will be resolved as soon as this https://github.com/AvaloniaUI/Avalonia/issues/11673 will be fixed.

**Comment by SKProCH** [comment]
Partially fixed in `11.0.999-cibuild0036218-beta` avalonia version.

**Comment by SKProCH** [comment]
Fixed in `11.0.0` Avalonia release
