### ISSUE TITLE
Scrollbar not shown in ScrollViewer

### ISSUE THREAD

**Issue by lxymahatma** [AvaloniaCommunity/Material.Avalonia#241]
Branch: avalonia-11-rc1

The demo project doesn't have scroll bars in its ScrollView page
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/66151783/7e369d23-0bfb-4826-83b4-44d6e7ea53df)

**Comment by NoizeDaemon** [comment]
Not sure if that's helpful, but I think I "solved" this by manually setting a width:

```
<Style Selector="ScrollBar:vertical">
	<Setter Property="Width" Value="50"/>
</Style>
```

That made it show up partially, but now it's cut off on the side:

![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/42150677/985cec8d-6698-49e5-ae99-976171c8b919)

Also I'm not sure what I'm doing wrong, but I cannot get modern oder minibar styles to work (basically I'd like the arrow buttons to be gone...)

**Comment by SKProCH** [comment]
Basic scrollbars should be fine now. Also, they support auto hiding. I planning to return modern scrollbars in the future.
