### ISSUE TITLE
switch pages may get struck[not bug]

### ISSUE THREAD

**Issue by mfkwgizhoujian** [AvaloniaCommunity/Material.Avalonia#245]
Avalonia Version: 11.0.0-rc1.1
Material.Avalonia Version: 3.0.0-avalonia11-preview4.179-nightly
Demo Branch: avalonia-11-rc1

When clicking on the menu item in the demo to switch pages, the first load may get stuck. How can I optimize it? thanks.

**Comment by SKProCH** [comment]
If you have any questions feel free to reopen the issue or create a new one (or the discussion)
