### ISSUE TITLE
Missing style for DatePicker TimePicker

### ISSUE THREAD

**Issue by Sophisticated-IS** [AvaloniaCommunity/Material.Avalonia#253]
**Avalonia** - 11.0.0-rc1.1
**Material.Avalonia** 3.0.0-avalonia11-preview5
**Problem:** style are not applied to DatePicker TimePicker. These controls have default avalonia style.

**Comment by SKProCH** [comment]
You can [install and use](https://github.com/AvaloniaCommunity/Material.Avalonia/wiki/Using-nightly-build-feed) latest nightly version [nuget](https://github.com/AvaloniaCommunity/Material.Avalonia/packages/572265) or wait until stable version of package has been released on Nuget feed.
