### ISSUE TITLE
The calendar control cannot display

### ISSUE THREAD

**Issue by qfmee** [AvaloniaCommunity/Material.Avalonia#258]
3.0.0-avalonia11-preview5.198-nightly

The calendar control cannot display !  this control It is very important that the upgrade has resulted in the inability to select a date. We hope to fix it as soon as possible. Thank you！

**Comment by SKProCH** [comment]
Duplicate of https://github.com/AvaloniaCommunity/Material.Avalonia/issues/250
I'll try to prioritize this in order to fix it asap.
