### ISSUE TITLE
ToggleButton status no change

### ISSUE THREAD

**Issue by qfmee** [AvaloniaCommunity/Material.Avalonia#259]
3.0.0-avalonia11-preview5.198-nightly

ToggleButton, there is no change in the status UI after selection！

**Comment by SKProCH** [comment]
Hello, @qfmee 

Can you try other control themes for toggle button (`FlatToggleButton`, `OutlineToggleButton`)?

**Comment by qfmee** [comment]
I try  (FlatToggleButton, OutlineToggleButton) is Same bug!



I added this code to solve the problem：
`<Style Selector="^:checked /template/ Border#PART_HoverEffect" >
			<Setter Property="Opacity" Value="{StaticResource ButtonPressedOpacity}" />
		</Style>`

**Comment by SKProCH** [comment]
Hmm, seems like this is an a tricky solution, cuz its breaking all our styles. I should figure out hot to implement a proper solution.

**Comment by lamah85** [comment]
Hello,

any updates on this issue?

**Comment by SKProCH** [comment]
Hello, @lamah85 

Currently no, since i working to complete https://github.com/AvaloniaCommunity/Material.Avalonia/issues?q=is%3Aopen+is%3Aissue+milestone%3Av3.0.0 to release 3.0.0, but i after 3.0.0 this is a on of high priority issues to fix. Currently you can use qfmee workaround, described above.

**Comment by lamah85** [comment]
Hello @SKProCH ,

thank you for your reply.

Due to the fact that i am not a big fan of workarounds i will just stick to an ordinary checkbox.

**Comment by marklam** [comment]
I'm not sure how to use the workaround above from code (I'm using Avalonia.FuncUI) so it would be very cool if this is back 'on the radar' for a fix.

**Comment by SKProCH** [comment]
Ok, I'll try to take a look at the weekend.

**Comment by marklam** [comment]
Thanks for your consideration!

**Comment by shuitai** [comment]
The issue is still there (3.5.0)

**Comment by SKProCH** [comment]
Should be fixed by https://github.com/AvaloniaCommunity/Material.Avalonia/pull/375
