### ISSUE TITLE
TreeViewItem Binding Bug

### ISSUE THREAD

**Issue by qfmee** [AvaloniaCommunity/Material.Avalonia#260]
3.0.0-avalonia11-preview5.198-nightly

TreeViewItem, there is an error in binding data. I will modify :

` <ContentPresenter DockPanel.Dock="Right"
                                    Name="{x:Static naming:PartNames.PartHeaderPresenter}"
                                    Content="{TemplateBinding Header}"
                                    Padding="{TemplateBinding Padding}" />`
 to :
`<ContentPresenter DockPanel.Dock="Right"
                                                      Name="{x:Static naming:PartNames.PartHeaderPresenter}"
                                                      Content="{TemplateBinding Header}"
                                                      ContentTemplate="{TemplateBinding HeaderTemplate}"
                                                      Padding="{TemplateBinding Padding}"
                                                      Focusable="False" />`
 and resolve it !

**Comment by SKProCH** [comment]
Fixed, thanks for help!
