### ISSUE TITLE
Is there a way for the Expander's header to be displayed on the left?

### ISSUE THREAD

**Issue by imJack6** [AvaloniaCommunity/Material.Avalonia#261]
As the title, I want Expander.Header to be displayed on the left, is there a way?

**Comment by imJack6** [comment]
> Hello, @imJack6
> 
> I think what you need to set the `ExpandDirection="Left"` or `ExpandDirection="Right"` actually.
> 
> Did it solve your problem?

No, what `ExpandDirection` changes is the direction of the Expander. I want to modify the position of the Header property in the Expander, because it is now `Center` by default, and I want it to be `Stretch`. The effect is as follows:
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/58357771/9fa19fce-dc7c-456a-a3d4-5e450a69185e)
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/58357771/ee74134a-7450-4bdd-aa59-3e374bd109f2)

**Comment by SKProCH** [comment]
I think you should try this:
```xaml
<Style Selector="Expander /template/ ToggleButton#PART_ToggleButton">
  <Setter Property="HorizontalContentAlignment" Value="Stretch"/>
</Style>
```

**Comment by imJack6** [comment]
> > > Hello, @imJack6
> > > I think what you need to set the `ExpandDirection="Left"` or `ExpandDirection="Right"` actually.
> > > Did it solve your problem?
> > 
> > 
> > No, what `ExpandDirection` changes is the direction of the Expander. I want to modify the position of the Header property in the Expander, because it is now `Center` by default, and I want it to be `Stretch`. The effect is as follows: ![image](https://user-images.githubusercontent.com/58357771/252301527-9fa19fce-dc7c-456a-a3d4-5e450a69185e.png) ![image](https://user-images.githubusercontent.com/58357771/252301568-ee74134a-7450-4bdd-aa59-3e374bd109f2.png)
> 
> https://github.com/MDModsDev/MuseDashModToolsUI/blob/1b25a7bf908421b701364a1f8833bbf74f4a2b5f/UI/Views/Tabs/ModManage.axaml#L449C48-L449C48
> 
> Try this?

> I think you should try this:
> 
> ```
> <Style Selector="Expander /template/ ToggleButton#PART_ToggleButton">
>   <Setter Property="HorizontalContentAlignment" Value="Stretch"/>
> </Style>
> ```
> 
> Did it help?

I tried both methods and it worked fine, thanks.
