### ISSUE TITLE
When switching themes, the border like TextBox will not update itself

### ISSUE THREAD

**Issue by imJack6** [AvaloniaCommunity/Material.Avalonia#262]
As in the title, the Avalonia version used is 11.0.0, and the Material.Avalonia is 3.0.0-avalonia11-preview5.202-nightly. In fact, the ComboBox control that looks similar to the TextBox in the video also has similar problems.

https://github.com/AvaloniaCommunity/Material.Avalonia/assets/58357771/0a56a685-68ae-4a38-b480-467f3cdc7c28

**Comment by SKProCH** [comment]
Ehh, please not again!

**Comment by SKProCH** [comment]
Should be fixed with https://github.com/AvaloniaUI/Avalonia/issues/12408

**Comment by SKProCH** [comment]
I probably should try to find a workaround for this...

**Comment by SKProCH** [comment]
I probably should try to find a workaround for this...

**Comment by SKProCH** [comment]
Currently this issue partially resolved, @imJack6, @melsawy93, @seikosantana. I've disabled the animation and currently it works fine now.

But this GitHub issue will remain open till problem was fixed from Avalonia side.

**Comment by SKProCH** [comment]
Fixed in the avalonia master branch - use `11.1.999-cibuild0043160-beta` or higher.
