### ISSUE TITLE
ComboBox doesn't show popup

### ISSUE THREAD

**Issue by JanTamis** [AvaloniaCommunity/Material.Avalonia#264]
On 3.0.0-avalonia11-preview5.203-nightly when the user clicks on the ComboBox the popup doesn't show.

**Comment by SKProCH** [comment]
I'll try to fix this today

**Comment by SKProCH** [comment]
Hmm, seems like this is working fine in demo. Can you provide a example, @JanTamis ?

**Comment by JanTamis** [comment]
hmm I'll take a look in my project

**Comment by njroyin** [comment]
The following code displays the combobox drop-down box on windows, but not on macos
`<ComboBox Grid.Row="2" Grid.Column="1" Margin="0,8" Width="200" Height="32" ItemsSource="{Binding DepartmentList}" >
					<ComboBox.ItemTemplate>
						<DataTemplate>
							<TextBlock Text="{Binding Value}" />
						</DataTemplate>
					</ComboBox.ItemTemplate>
				</ComboBox>`
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/16891922/43210a36-9141-46be-97f3-13eb1981754d)
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/16891922/bc96e4e3-24c1-4db9-b0a2-7ead291df54e)

**Comment by JanTamis** [comment]
if I set IsDropDownOpen to true then it is visible (I am using MacOS)

**Comment by JanTamis** [comment]
So after testing it it doesn't work with the fluent theme, so it is an bug in Avalonia.
