### ISSUE TITLE
Implement modern theme for ScrollViewer

### ISSUE THREAD

**Issue by PerfectlyFineCode** [AvaloniaCommunity/Material.Avalonia#265]
I currently use Avalonia 11.0.0-rc2.2 (latest dotnet template).
With Material.Avalonia version 3.0.0-avalonia11-preview5.205-nightly.

ScrollViewer modern style is not being applied. I still get Fluent theme.

## App.xaml
```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:themes="clr-namespace:Material.Styles.Themes;assembly=Material.Styles"
             xmlns:materialIcons="clr-namespace:Material.Icons.Avalonia;assembly=Material.Icons.Avalonia" 
             xmlns:local="using:Foo"
             xmlns:dialogHostAvalonia="clr-namespace:DialogHostAvalonia;assembly=DialogHost.Avalonia"
             xmlns:styles="clr-namespace:Material.Styles;assembly=Material.Styles"
             x:Class="Foo.App"
             RequestedThemeVariant="Default">
     <Application.DataTemplates>
         <local:ViewLocator/>
     </Application.DataTemplates>

    <Application.Styles>
        <themes:MaterialTheme BaseTheme="Dark" PrimaryColor="Purple" SecondaryColor="Lime" />
        <materialIcons:MaterialIconStyles />
        <dialogHostAvalonia:DialogHostStyles />
        <styles:MaterialToolKit />
        
        <!-- Material Design DataGrid -->
        <StyleInclude Source="avares://Material.DataGrid/DataGrid.xaml" />

    </Application.Styles>
</Application>
```

## MainView
```xml
<ScrollViewer>
    <!-- Content here -->
</ScrollViewer>
```

I pretty much ripped the demo source code, it still isn't showing for me.

![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/70201838/f10ce271-bcf8-4e46-b1ee-d8a38064229d)

**Comment by SKProCH** [comment]
Hello, @PerfectlyFineCode 

As far as i can remember, there is a lot of issues with ScrollViewers after Avalonia 11 release. So, i've ported and fixed only this style (with auto-hide support). I've planning to return back old themes for all others controls soon, but i don't have a lot of time for this, sorry. Currently i working for TimePicker (and Clock control), since Material.Avalonia doesn't hava any style for this.

**Comment by SKProCH** [comment]
Added as `MaterialModernScrollViewer`
