### ISSUE TITLE
Dark mode text display colors are displayed incorrectly in the browser

### ISSUE THREAD

**Issue by Red6789** [AvaloniaCommunity/Material.Avalonia#271]
https://github.com/Red6789/AboutMaterialDesignForAvalonia/tree/main/TextColorProblem
This is a simple code, Just run TextColorProblem.Browser, you can know what is problem.
Thank you for your patience in checking.

**Comment by Red6789** [comment]
Avalonia 11.0.2
Material.Avalonia 3.0.0-avalonia11-preview5.216-nightly

**Comment by SKProCH** [comment]
Hello, @Red6789 

I can't launch your app. Here is the error:
```
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\SKProCH\RiderProjects\AboutMaterialDesignForAvalonia\TextColorProblem\TextColorProblem.Browser\bin\Debug\net7.0\browser-wasm\'.          Failed to run as a self-contained app.                                                                                              - The application was run as a self-contained app because 'C:\Users\SKProCH\RiderProjects\AboutMaterialDesignForAvalonia\TextColorProblem\TextColorProblem.Browser\bin\Debug\net7.0\browser-wasm\TextColorProblem.Browser.runtimeconfig.json' did not specify a framework.                                                                                                                            - If this should be a framework-dependent app, specify the appropriate framework in 'C:\Users\SKProCH\RiderProjects\AboutMaterialDesignForAvalonia\TextColorProblem\TextColorProblem.Browser\bin\Debug\net7.0\browser-wasm\TextColorProblem.Browser.runtimeconfig.json'.
```

**Comment by SKProCH** [comment]
Well, i can run it on my linux laptop. I reproduce the issue, but i don't know what to do with that. Seems like there is no dev tools or even debugger. 

I'll try to investigate the problem, but actually at the moment i don't know what i can do. If you manage to get any info about it - please contact me here.

**Comment by SKProCH** [comment]
Does this reproducible with Fluent or Simple avalonia themes?

**Comment by Red6789** [comment]
I tried avalonia theme, and this problem did not reproducible.

**Comment by Red6789** [comment]
> Does this reproducible with Fluent or Simple avalonia themes?

I tried avalonia theme, and this problem did not reproducible.

**Comment by Red6789** [comment]
I found the cause of the problem，
https://github.com/AvaloniaCommunity/Material.Avalonia/blob/dev/Material.Styles/Window.xaml
Because Wasm does not have the concept of form, it is UserControl, so it does not inherit the default style of window.
The repair is also very simple, just add in the following control style
<Setter Property="TextElement.Foreground" Value="{DynamicResource MaterialDesignBody}" />
https://github.com/AvaloniaCommunity/Material.Avalonia/blob/dev/Material.Styles/UserControl.xaml

**Comment by Red6789** [comment]
It is best to judge the Browser through ApplicationLifetime, and then use a style similar to windows
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/131952234/358c3647-b6db-42ae-890b-a2628cdcce42)
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/131952234/c524afd3-1755-41de-9791-f64775fee794)

**Comment by Red6789** [comment]
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/131952234/0eb4c4c3-9c19-4efb-87a8-1f668bde76cf)
Currently I'm solving the problem by first doing

**Comment by SKProCH** [comment]
@Red6789 can you try the latest nightly?
