### ISSUE TITLE
Support icon button

### ISSUE THREAD

**Issue by Red6789** [AvaloniaCommunity/Material.Avalonia#274]
Do you have plans to support icon buttons?
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/131952234/549de582-4269-45a0-ae2e-343be0900a22)

**Comment by SKProCH** [comment]
Hello, @Red6789 

You can probably use Flat buttons for now. 

Also, i mark this issue as enhancement and eventually this is will be implemented. (or you can make a PR, if you want)
