### ISSUE TITLE
Unify brushes names

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaCommunity/Material.Avalonia#277]
Currently we have a different names for brushes:
- PrimaryHueLightForeground**Brush**
- ValidationError**Brush**
- **MaterialDesign**Background
- **MaterialDesign**Paper
- etc
Also, in `MaterialPredefinedBaseColors.axaml` brushes have a slightly different names (seems like its is bug).

I want to make all brushes follow the same naming style. It would break all user defines custom styles (if i don't do a fallback or something). But i think, what we should do this now (ASAP), to include it to `3.0.0` release, because the far it goes - the more users will use the library and the more styles will be broken.

Currently i want to use the **Material**NAME**Brush** naming convention for brushes. And **Material**NAME**Color** for underlying colors (if necessary).

If you want to discuss it - feel free to leave a comments.

**Comment by JanTamis** [comment]
So i.e you want to change PrimaryHueLightForegroundBrush to MaterialPrimaryHueLightForegroundBrush?

**Comment by SKProCH** [comment]
> So i.e you want to change PrimaryHueLightForegroundBrush to MaterialPrimaryHueLightForegroundBrush?

Probably yes. I'm, not quite sure about Primary and Secondary brushes, but i thing what all other brushes (such as MaterialDesignBackground, MaterialDesignPaper, etc) should be renamed.

**Comment by JanTamis** [comment]
Let me know when you know what the names should be and i will try to rename them.

**Comment by SKProCH** [comment]
@JanTamis 
I think what we should unify the Primary and Secondary brushes too. So, **Material**NAME**Brush**, like:

- MaterialPrimaryHueLightBrush
- MaterialSecondaryHueLightForegroundBrush
- MaterialBackgroundBrush
- MaterialSnackbarRippleBrush
- MaterialSnackbarRippleBrush
- etc

Also, it would be cool, if you create a fallback resources (with older names)

**Comment by JanTamis** [comment]
I'll take a look at what i can do

**Comment by JanTamis** [comment]
@SKProCH Shall i base my branch from the Master branch?

**Comment by SKProCH** [comment]
> @SKProCH Shall i base my branch from the Master branch?

Yes
