### ISSUE TITLE
Removing styles / underline from textbox

### ISSUE THREAD

**Issue by timkicker** [AvaloniaCommunity/Material.Avalonia#278]
Hello c:

I do want to make the text in my TextBlock selecteable. Various online sources suggest to use a TextBox and set `IsReadOnly`to true. However this does not look right in combination with this theme, as the "underline" still remains visible. :

**TextBlock:**

![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/33966128/41897c3b-26f1-41e2-a3ac-9dbf1af861d4)

**TextBox:**
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/33966128/1b55d851-bc7c-451d-bee1-c95904fd4a1d)

I tried overwriting the style with no success.

May anyone help me resolve this issue?
Thanks in advance! c:

**Comment by SKProCH** [comment]
Hello, @timkicker 

You can try the `SelectableTextBlock` control. Does it helps?

**Comment by timkicker** [comment]
Thanks!

You just saved me a ton of work. It's weird though that this controls is not documented enough and is not that obvious to find using a search engine. Also the issues on the Avalonia repo regarding "RichTextBoxes" or the official doc's do not seem to link to it.

But yes, this resolved my issue.
c:

**Comment by SKProCH** [comment]
Yep, seems like SelectableTextBlock isn't documented, this weird. So, anyway, it's nice, what you solved your problem.
