### ISSUE TITLE
Datagrid theme makes the datagrid not visible

### ISSUE THREAD

**Issue by HeadhunterXamd** [AvaloniaCommunity/Material.Avalonia#281]
Hi I am using the latest nuget version 3.0.0-avalonia11-preview6.13-nightly (both the base package and the datagrid package)
I have a simple PCSC cardreader that pushes an card onto a datagrid, this datagrid sadly is invisible in this theme (dark or light)

Here is my app.axaml:
<img width="829" alt="image" src="https://github.com/AvaloniaCommunity/Material.Avalonia/assets/8035760/5ed294e7-4c3f-4349-afac-703a975a51a9">

Here is the window:
<img width="1129" alt="Screenshot 2023-08-18 at 16 18 30" src="https://github.com/AvaloniaCommunity/Material.Avalonia/assets/8035760/46468f1b-5b1f-405e-9100-2770ff21a487">

Is this a known issue or do I need to do something in the app.axaml?

**Comment by SKProCH** [comment]
Hello, @HeadhunterXamd 

If you add `<StyleInclude Source="avares://Material.Avalonia.DataGrid/DataGrid.xaml" />` to your App.axaml, does this fix a problem?

**Comment by SKProCH** [comment]
@HeadhunterXamd does it works with `3.0.0-avalonia11-preview6.15-nightly`?

**Comment by JohnKesko** [comment]
I just had the same issue and upgraded to Material.Avalonia 3.0.0-avalonia11-preview6.17-nightly + Material.Avalonia.DataGrid 3.0.0-avalonia11-preview6.17-nightly.

That solved it for me and I don't have Fluent Theme installed anymore.
