### ISSUE TITLE
How to change row color in datagrid?

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaCommunity/Material.Avalonia#293]
### Discussed in https://github.com/AvaloniaCommunity/Material.Avalonia/discussions/292

<div type='discussions-op-text'>

<sup>Originally posted by **Seartur** September 17, 2023</sup>
Hi. Why can't I change the color in row in datagrid?

`<DataGrid Height="1200" Width="1000"  x:Name="AlarmsDG" RowBackground="BlueViolet" AutoGenerateColumns="true"></DataGrid>`

How does "RowBackground" work?
</div>

**Comment by SKProCH** [comment]
@Seartur can you try the latest nightly and confirm if issue fixed?

**Comment by Seartur** [comment]
In 3.0.0.36-nightly  work!

**Comment by Seartur** [comment]
@SKProCH In 3.0.0.36-nightly work!
