### ISSUE TITLE
'MaterialPaperBrush' not found

### ISSUE THREAD

**Issue by NoizeDaemon** [AvaloniaCommunity/Material.Avalonia#295]
Hi :) 

Not sure if this is related to the renaming of brushes in #286  or if I made a mistake somewhere else.
I'm getting this error at runtime:
`"System.Collections.Generic.KeyNotFoundException" in Avalonia.Markup.Xaml.dll`
`Static resource 'MaterialPaperBrush' not found.`

However, the previewer is able to find those ressources (both with old and new names):
```xaml
<Rectangle Fill="{DynamicResource PrimaryHueLightBrush }" />
<Rectangle Fill="{DynamicResource MaterialPrimaryLightBrush }" />
<Rectangle Fill="{DynamicResource MaterialDesignPaper}" />
<Rectangle Fill="{DynamicResource MaterialPaperBrush}" />
<Rectangle Fill="{DynamicResource SecondaryHueMidBrush}" />
<Rectangle Fill="{DynamicResource MaterialSecondaryMidBrush}" />
```
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/42150677/9c425fe6-7d97-4518-87f0-6594e745d31d)

Further Info:

My projects [repo](https://github.com/NoizeDaemon/MDW) is still fairly minimal, if that is helpful.

I just started a new Avalonia Project for Desktop/Web and added some essential packages:

```xml
  <PackageReference Include="Avalonia" Version="11.0.4" />
  <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.0.4" />
  <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.4" />
  <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.4" />
  <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.4" />
  <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
  <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.4" />
  <PackageReference Include="DialogHost.Avalonia" Version="0.7.7" />
  <PackageReference Include="Material.Avalonia" Version="3.0.1" />
  <PackageReference Include="Material.Avalonia.DataGrid" Version="3.0.1" />
  <PackageReference Include="Material.Avalonia.Dialogs" Version="3.0.1" />
  <PackageReference Include="Material.Icons.Avalonia" Version="2.0.1" />
  <PackageReference Include="ReactiveUI.Fody" Version="19.4.1" />
```
   

Not sure if I am using incompatible package versions or if I did the setup incorrectly in the `App.xaml`:

```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
			 xmlns:styles="clr-namespace:Material.Styles;assembly=Material.Styles"
			 xmlns:themes="clr-namespace:Material.Styles.Themes;assembly=Material.Styles"
			 xmlns:icons="clr-namespace:Material.Icons.Avalonia;assembly=Material.Icons.Avalonia"
			 xmlns:dialog="clr-namespace:DialogHostAvalonia;assembly=DialogHost.Avalonia"
			 xmlns:local="using:MarkDownWiki"
             x:Class="MarkDownWiki.App">
        ...

	<Application.Styles>
		<FluentTheme />
		<StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Fluent.xaml"/>
		<themes:MaterialThemeBase />
		<icons:MaterialIconStyles />
		<styles:MaterialToolKit />
		<dialog:DialogHostStyles />
	</Application.Styles>
</Application>
```

I'd appreciate any help.

**Comment by SKProCH** [comment]
Hello, @NoizeDaemon

Currently I can't reach my PC, so I can't test your project, but I have one assumption.

As far as I remember, MaterialPaperBrush is the theme specific brush. So, you probably need to use MaterialTheme instead of MaterialThemeBase, or setup the theme for MaterialThemeBase in code behind byself. 

Does it helps?

**Comment by SKProCH** [comment]
Yep, tested it, and seems like this is works:  
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/29896317/94c56e61-bbc3-49c4-8fd6-c641d9e21063)

**Comment by NoizeDaemon** [comment]
Yes, that works! :)

No error on runtime. 

For the brushes, both old and new paper brush names seem to work, for the primary/secondary brushes the new ones work.


```xaml
<Rectangle Fill="{DynamicResource PrimaryHueLightBrush }" />
<Rectangle Fill="{DynamicResource MaterialPrimaryLightBrush }" />
<Rectangle Fill="{DynamicResource MaterialDesignPaper}" />
<Rectangle Fill="{DynamicResource MaterialPaperBrush}" />
<Rectangle Fill="{DynamicResource SecondaryHueMidBrush}" />
<Rectangle Fill="{DynamicResource MaterialSecondaryMidBrush}" />
```
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/42150677/0be32e13-6ce8-48f8-b182-88749a16c4e6)

Thank you very much!
