### ISSUE TITLE
TabStripItem :selected style references wrong ancestor

### ISSUE THREAD

**Issue by kevkov** [AvaloniaCommunity/Material.Avalonia#298]
https://github.com/AvaloniaCommunity/Material.Avalonia/blob/e389f964e9e3082b5284abda208b3edfeb1d24c0/Material.Styles/Resources/Themes/TabStripItem.axaml#L46

As a result the item is not visible when the item is selected. I think the ancestor type should be TabStrip.

**Comment by SKProCH** [comment]
Thanks!
