### ISSUE TITLE
Flyout styling

### ISSUE THREAD

**Issue by Andy-DG** [AvaloniaCommunity/Material.Avalonia#309]
Does this not automatically style flyouts when using;
<Window.Styles>
        <themes:MaterialTheme BaseTheme="Dark" PrimaryColor="Indigo" SecondaryColor="Amber" />
    </Window.Styles>
    
    Other elements seem to get styled to the theme automatically, but the flyouts not?
    
    This is the Flyout i'm using:
    <Window.Resources>
        <Flyout x:Key="AddSceneFlyout" 
                Placement="TopEdgeAlignedLeft">
            <StackPanel Margin="10" VerticalAlignment="Top">
                <TextBox Text="{Binding Scene.Name}" Watermark="Enter scene name" Width="370" Margin="0,0,0,10" ToolTip.Tip="Enter the name of the scene"/>
                <ComboBox ItemsSource="{Binding HotkeyOptions}" SelectedItem="{Binding Scene.Hotkey}" Width="370" Margin="0,0,0,10" ToolTip.Tip="Select a hotkey"/>
                <Button Content="Add Scene" Command="{Binding AddScene}"></Button>
            </StackPanel>
        </Flyout>  
    </Window.Resources>

**Comment by SKProCH** [comment]
Hello, @Andy-DG 

Seems like you use Flyouts wrong. Quick example shows that flyouts working as expected:
```
<Button Content="123">
  <Button.Flyout>
    <Flyout>
      <TextBlock>Test</TextBlock>
    </Flyout>
  </Button.Flyout>
</Button>
```
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/29896317/eb5e6eee-f58f-49e4-9281-1a848bd61d63)

If i missing something, please attach a minimal reproduceable example.

**Comment by SKProCH** [comment]
Closing this issue as staled. Feel free to reopen it or create a new one if the problem persists or you have any questions.
