### ISSUE TITLE
Request to add DataGrid style

### ISSUE THREAD

**Issue by rakuten** [AvaloniaCommunity/Material.Avalonia#32]
I just want to tell you that material.avalonia project is really great.

But I found that the style of DataGrid has not been defined yet.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.DataGrid/Themes/Default.xaml

**Comment by appleneko2001** [comment]
DataGrid style are still WIP (working in progress). It looks like this now:

![](https://user-images.githubusercontent.com/38249047/104083274-a99f1a00-5280-11eb-8d3c-fa4d60ad9f46.png)

DataGrid with other controls (buttons, checkbox etc.) is still not tested. So I don't know how it looks like, but we will know later.

**Comment by SKProCH** [comment]
Seems like this is working.
