### ISSUE TITLE
In some cases ,button the "pointerover" state of the mouse cannot be restored after leaving

### ISSUE THREAD

**Issue by qfmee** [AvaloniaCommunity/Material.Avalonia#320]
Avalonia：11.0.5
Material.Avalonia：3.1.0
windows11

When multiple buttons are adjacent and the mouse moves quickly within them, due to animation transition issues, the "pointerover" state of the mouse cannot be restored after leaving.

such as this video

https://github.com/AvaloniaCommunity/Material.Avalonia/assets/74282924/ee99db6f-fa06-4ab2-acdd-8f9897c6e5a1

**Comment by qfmee** [comment]
Through shadows, it can be seen that their final states are different！
<img width="612" alt="8d21ac2ffe64c1035dd695913deb003" src="https://github.com/AvaloniaCommunity/Material.Avalonia/assets/74282924/4ac81627-1aea-42ab-8b34-c6a1e9f51d67">

**Comment by SKProCH** [comment]
Hello, @qfmee 

Can you look at the devtools to see, if there is :pointerover pseudoclasses on such like buttons?
