### ISSUE TITLE
Add support for localizing context menu item names.

### ISSUE THREAD

**Issue by Jackhammer88** [AvaloniaCommunity/Material.Avalonia#322]
### Description:
Currently, the names of items in the context menu of our application are hard-coded in English (Copy, Paste, Cut, Select all). However, for better user accessibility and usability, we would like to propose adding support for localizing the names in the context menu based on the language set in the user's system.

### Expected Behavior:

Automatically adapt the context menu item names to the language set in the user's system.
Allow users to override this language setting within the application if they prefer a different language.
### Additional Information:
This feature will enhance the experience for users, as it will display context menu item names in the language of their system, making our application more accessible and user-friendly. Users who prefer a different language can still have the flexibility to customize it within the application settings.
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/19895415/b8366a5d-47ed-476c-a569-30993fd128a8)

**Comment by SKProCH** [comment]
Should work same way as Avalonia does. For keys look at https://github.com/AvaloniaCommunity/Material.Avalonia/blob/master/Material.Styles/InvariantResources.xaml
