### ISSUE TITLE
Border Brush Does Not Change When Switching Themes

### ISSUE THREAD

**Issue by Jackhammer88** [AvaloniaCommunity/Material.Avalonia#325]
### Description
I've encountered an issue with Material.Avalonia where the Border element's brush does not immediately update its color to match the current theme after switching themes. However, the color does update correctly after moving the application window.

### Steps to Reproduce

1. Launch the application.
2. Observe the Border element's color in the current theme.
3. Click the "Switch theme" button to change the theme.
4. Notice that the Border's brush color remains unchanged and does not match the new theme.
5. Move the application window around.
6. After moving the window, observe that the Border's brush color updates to align with the new theme.

### Expected Behavior
When switching themes, the Border element's brush should update its color to align with the new theme settings.

### Actual Behavior
The Border retains its original brush color, leading to a mismatch with the overall theme of the application after a theme switch.

### Environment
Material.Avalonia version: 3.1.1
Avalonia version: 11.0.5
OS: Astra linux
.NET version: 8.100
### Additional Context
This issue seems to be consistent across different themes and does not depend on the specific colors of the themes. The problem persists even after resizing or moving the application window.

![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/19895415/c90e68c2-3119-41b5-9e19-5755a6c743cb)
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/19895415/f2f3cb6a-a6b6-49d0-880a-c84cf5c7838f)

[https://github.com/Jackhammer88/SwitchThemeError](url)

**Comment by SKProCH** [comment]
Fixed in the avalonia master branch - use `11.1.999-cibuild0043160-beta` or higher.
