### ISSUE TITLE
Strange border behavior on Outline buttons and Datagrid

### ISSUE THREAD

**Issue by codealle** [AvaloniaCommunity/Material.Avalonia#328]
### Description

My project uses buttons that use the MaterialOutlineButton style and Datagrid controls. Since I updated Material.Avalonia to version 3.1.1, the borders are not painted unless the window where they are loaded is resized.
They are also not painted in the previewer unless you make a change in the XAML

### Steps to Reproduce

1. Create a project in Avalonia.
2. Add the Material.Avalonia 3.1.1 or higher packages (also fails)
3. Add buttons with the MaterialOutlineButton style and a Datagrid with BorderThickness="2"
4. Launch the project.
5. You see the buttons without borders and the Datagrid also without borders, if you change the size of the window the borders appear.

### Expected Behavior

The buttons and Datagrid should appear as usual without having to resize the window.

### Actual Behavior

The borders are not visible unless you resize the window.

### Environment

Material.Avalonia version: 3.1.1  or superior
Avalonia version: 11.0.6  
OS: Windows 10
.NET version: 7.0 or 8.0

Buttons and Datagrid on previewer
![Designer](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/55779290/060aeb67-def6-4d75-a55c-ca648900e0b4)

Buttons and Datagrid on runtime
![Runtime](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/55779290/98e7d72e-27f9-460e-a357-f57020cd6f64)

Buttons and Datagrid after changing the window size
![Resized](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/55779290/d71562de-6fa3-4f73-ab50-9cd706e572c4)

**Comment by SKProCH** [comment]
Looks like a bug with https://github.com/AvaloniaUI/Avalonia/issues/12408

I'll try to find a workaround.

**Comment by SKProCH** [comment]
Fixed in the avalonia master branch - use `11.1.999-cibuild0043160-beta` or higher.
