### ISSUE TITLE
Not Working in Browser

### ISSUE THREAD

**Issue by CastelloBrancoTecnologia** [AvaloniaCommunity/Material.Avalonia#333]
An empty avalonia App Not show "Welcome to AValonia and shows a blank broser window"

		<themes:MaterialTheme BaseTheme="Light" PrimaryColor="Indigo" SecondaryColor="Blue" />

but if i comment in app.xaml the material style, it show the message normaly

`<!--<themes:MaterialTheme BaseTheme="Light" PrimaryColor="Indigo" SecondaryColor="Blue" />-->`

I am using avalonia 11.0.6 in browser solution and Material.Avalonia 3.1.3

all other plataforms works ok

**Comment by dtavlikos** [comment]
I am having the same exact issue.

**Comment by SKProCH** [comment]
Any ideas about that?

**Comment by dtavlikos** [comment]
@SKProCH No idea what to look for, I just started looking into Avalonia a few days ago.

**Comment by SKProCH** [comment]
Seems like this is an Avalonia's bug, more info [here](https://github.com/AvaloniaUI/Avalonia/issues/14022#issuecomment-1869383204).

## Fix 
Go to `*.Browser/AppBundle/main.js` and replace `runMainAndExit` with `runMain`:
```js
await dotnetRuntime.runMain(config.mainAssemblyName, [window.location.search]);
```

After that run `dotnet build` and everything should be fixed.

**Comment by dtavlikos** [comment]
@SKProCH This fixed the issue, thanks!
