### ISSUE TITLE
Hey guys, please add a datagrid demo!

### ISSUE THREAD

**Issue by wj8400684** [AvaloniaCommunity/Material.Avalonia#338]
Hey guys, please add a datagrid demo!

**Comment by SKProCH** [comment]
Hello, @wj8400684 

Currently there are more important bugs or enchantments to complete, so I don't think I can do it quickly, but you can always send a PR if you want.

**Comment by wj8400684** [comment]
ok

**Comment by SKProCH** [comment]
There is no need to close this issue, because I think sooner or later it will be implemented.
