### ISSUE TITLE
MaterialTextBoxBorderBrush is wrong when switching out theme at runtime

### ISSUE THREAD

**Issue by Mrxx99** [AvaloniaCommunity/Material.Avalonia#348]
### Usage Information

3.4.0 / 11.0.9 / Windows 10

### Description

Switching out the theme at runtime while also switching between light and dark will not update the MaterialTextBoxBorderBrush used e.g. in TextBox and ComboBox correctly leading to either a black brush on dark theme (which is barly visible) or a white brush on Light theme (which is completely invisible)

![grafik](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/33566379/2c1e960e-6269-4d4c-a539-40a6efb63ab3)

![grafik](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/33566379/604c6e25-69b5-4a7d-afaf-48f616832fba)

### Reproduction Steps

A:
1. check out the test repository https://github.com/Mrxx99/MaterialAvaloniaTest
2. look at the textbox/combobox underline or the last border
3. switch the theme with the toggle to dark
4. look again at the textbox/combobox underline or the lasts border

B:
1. Go to App.axaml and change BaseTheme to Dark
2. look at the textbox/combobox underline or the lasts border
3. switch the theme with the toggle to light
4. look again at the textbox/combobox underline or the lasts border

### Expected Behavior

Switchig between the light and dark theme updates the MaterialTextBoxBorderBrush correctly so e.g. TextBox or ComboBox are updated accoringly to the theme change

### Actual Behavior

Brush is not updated correctly when switching themes, leading to barely visible to completely invisible lines in TextBox and ComboBox

### Could you help with a pull-request?

No

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SKProCH** [comment]
Yep, this is has been commented due to https://github.com/AvaloniaUI/Avalonia/issues/12408

But since it has been resolved now I should return it back.

**Comment by SKProCH** [comment]
Should be resolved in `3.4.1`. Reopen issue if it persist,

**Comment by Mrxx99** [comment]
Thanks very much, issue is fixed
