### ISSUE TITLE
The flyout uses the opposite theme variant

### ISSUE THREAD

**Issue by JanSCPA** [AvaloniaCommunity/Material.Avalonia#354]
### Usage Information

3.4.2 / 11.0.9 / Win & Linux

### Description

Hi!

the flyout using the dark variant uses the light style and vice versa.

### Reproduction Steps

For reproduction the ButtonDemo.axaml-Page from the Demo can be used:

```
<Button Theme="{StaticResource MaterialOutlineButton}" Classes="light" Content="Test Button With Flyout"  >
  <Button.Flyout>
    <Flyout>
      <TextBox Watermark="Test" />
    </Flyout>
  </Button.Flyout>
</Button>

```
### Expected Behavior

Dark Variant: Flyout using Dark-Styles

### Actual Behavior

Dark Variant: Flyout using Light-Styles
Light Variant: Flyout using Dark-Styles

### Could you help with a pull-request?

No

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SKProCH** [comment]
I'll take a look
