### ISSUE TITLE
DataGrid could not be shown in Avalonia 11.1.0-beta1

### ISSUE THREAD

**Issue by ismlsmile** [AvaloniaCommunity/Material.Avalonia#357]
### Usage Information

3.4.2/11.1.0-beta1/Windows

### Description

DataGrid could not be shown, just blank

### Reproduction Steps

Just a plain Datagrid

### Expected Behavior

Show correctly

### Actual Behavior

Not shown

### Could you help with a pull-request?

No

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SKProCH** [comment]
Seems like Material currently isn't fully compatible for 11.1.0 for now. I'll take a look.

**Comment by SKProCH** [comment]
Seems like I can't reproduce it - everything works fine. Did you install `Material.Avalonia.DataGrid` package?

**Comment by ismlsmile** [comment]
I am sorry I could not reproduce it either. Maybe I forget to install Material.Avalonia.DataGrid package.
