### ISSUE TITLE
Demo code popup issues on Mac Chrome, Safari and Desktop

### ISSUE THREAD

**Issue by buzzware** [AvaloniaCommunity/Material.Avalonia#361]
### Usage Information

https://avaloniacommunity.github.io/Material.Avalonia on Mac Chrome Version 123.0.6312.87 (Official Build) (x86_64) and Safari  17.3.1 (19617.2.4.11.12)

### Description

1) The demo project (https://avaloniacommunity.github.io/Material.Avalonia/) code display popup text on Mac Chrome has no cursor and is not selectable. It freezes the browser and you get a "Page Unresponsive" popup.
2) On Mac Safari the code button freezes the browser without showing the popup (I have seen the popup appear only once in many attempts).
3) The Demo project on Desktop on Mac (not a macos build) the code popup has a cursor and I can copy and paste with it, but the normal selection text highlight is invisible, so it doesn't look like you can select it. The Reset button crashes the app, and the Apply button shows "Dynamic code generation is not supported on this platform." (which is properly highlighted on selection and does copy and paste).

### Reproduction Steps

1. Run the demo
2. Select the Buttons page
3. tap any "</>" code button 

### Expected Behavior

Code should be selectable and highlight as selected

### Actual Behavior

Crashes the browser, page unresponsive

### Could you help with a pull-request?

No

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SKProCH** [comment]
WASM bug is actually a known issue, but invisible selection in desktop is something I missed, actually. I'll try to fix this, thanks!

**Comment by SKProCH** [comment]
Desktop bugs and selection color should be fixed now. As for WASM - currently investigate an TextMate problem.
