### ISSUE TITLE
Provide a minimal example repository

### ISSUE THREAD

**Issue by buzzware** [AvaloniaCommunity/Material.Avalonia#362]
The "kitchen sink" style demo is great, but its also useful for beginners to have a complete minimal project showing a few controls.
I created this https://github.com/buzzware/AvaloniaMaterialTest which could be use as a starting point.

**Comment by SKProCH** [comment]
Integrated this link to getting started wiki page: https://github.com/AvaloniaCommunity/Material.Avalonia/wiki/Getting-started
