### ISSUE TITLE
Scroll Inertia Broken by MaterialTheme

### ISSUE THREAD

**Issue by LyleRolleman-plst** [AvaloniaCommunity/Material.Avalonia#363]
### Usage Information

v3.4.3 / 11.2.999-cibuild0046730-alpha / iOS 17.4.1 (probably Android as well)

### Description

When using the MaterialTheme in my Avalonia app, it breaks scroll inertia for all ScrollViewers (including things like ListBox)

If I use the FluentTheme however, it works fine

Example app:
[ScrollViewerInertiaTest.zip](https://github.com/AvaloniaCommunity/Material.Avalonia/files/14793708/ScrollViewerInertiaTest.zip)

### Reproduction Steps

Open the included test app and swipe/flick up and down

### Expected Behavior

Scrolling should have inertia when I release touch

### Actual Behavior

When using MaterialTheme, there is no inertia. The scroll stops dead upon release of touch. Switching out the themes in App.axaml resolves the issue

### Could you help with a pull-request?

No

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SKProCH** [comment]
I'll take a look
