### ISSUE TITLE
Left side corner radius value is not respected by the progress bar

### ISSUE THREAD

**Issue by PapLabros** [AvaloniaCommunity/Material.Avalonia#372]
### Usage Information

Material.Avalonia 3.5.0 / Avalonia 11.0.10 / Windows 11

### Description

The **top left** and the **bottom left** corners of the progress bar are not affected when specifying a CornerRadius and the value of progress bar is greater than zero. This is due to the rectangle that is used for indicating the progress is not clipped by the main progress bar border. If ClipToBounds is set to true to the **PART_RootBorder** of the style, the issue is fixed.

### Reproduction Steps

1. Add a progress bar
2. Set its value to 30
3. Set its corner radius to 10

### Expected Behavior

1. Add a progress bar
2. Set its value to 30
3. Set its corner radius to 10

The corner radius should be applied to the top left and the bottom left corners of the progress bar.

### Actual Behavior

1. Add a progress bar
2. Set its value to 30
3. Set its corner radius to 10

The corner radius is not applied to the top left and the bottom left corners of the progress bar.

### Could you help with a pull-request?

Yes

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SKProCH** [comment]
Yep, seems like this is a bug. You can open an pull request, and iI'll merge it.
