### ISSUE TITLE
Support Visual Studio development

### ISSUE THREAD

**Issue by odalet** [AvaloniaCommunity/Material.Avalonia#374]
### Usage Information

master branch / 11.0.10 / Windows

### Description

I tried to build `Material.Avalonia` from Visual Studio 2022, but it fails when building the example application because the `ShowMeTheXaml.Avalonia` source generator does not run.

I've filed an issue detailing what could be done here: <https://github.com/AvaloniaUtils/ShowMeTheXaml.Avalonia/issues/4>

### Reproduction Steps

* Open `Material.Avalonia.sln` in Visual Studio 2022
* Build ther solution

### Expected Behavior

The solution builds in Visual Studio

### Actual Behavior

The build fails saying it can't find the `UseXamlDisplay` extension method.
A warning is also issued saying it could not load the source generator

More details here: <https://github.com/AvaloniaUtils/ShowMeTheXaml.Avalonia/issues/4>

### Known Workarounds

`dotnet build` and Rider have no issue building the solution

### Could you help with a pull-request?

Yes

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SKProCH** [comment]
@odalet can you test it now?

**Comment by odalet** [comment]
That was quick! Everything is working perfectly now. Thanks!
