### ISSUE TITLE
TextBox text selection/copy doesn't work

### ISSUE THREAD

**Issue by LyleRolleman-plst** [AvaloniaCommunity/Material.Avalonia#376]
### Usage Information

3.6.0

### Description

Trying to select text within a TextBox doesn't work properly on Android/iOS. Tapping and holding brings up a Cut, Copy, Paste and Select All context menu, but cut and copy remain disabled with no ability to select the text, except Select All which then hides the context menu, making it pretty useless. 

This isn't a problem when using the default FluentTheme so something in here seems to be overriding and breaking the behaviour

### Reproduction Steps

Attempt to select TextBox with text using usual tap/hold/drag. Observe doesn't select, with aforementioned broken context menu. Drag handles from base Avalonia/FluentTheme do not appear

### Expected Behavior

I should be able to select text in a TextBox to copy

### Actual Behavior

See description

### Could you help with a pull-request?

No

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SKProCH** [comment]
I'll take a look.

**Comment by SKProCH** [comment]
Seems like Material textbox behaves as default Fluent one. Here is the demo:

https://github.com/AvaloniaCommunity/Material.Avalonia/assets/29896317/ee82491c-91c5-43ef-bbc7-99f55b25f76a

I've also doesn't see any drag handles from avalonia. May be I'm missing something? Can you share the sample app with proper avalonia's TextBox behavior?

**Comment by SKProCH** [comment]
Oh, probably the 11.1.0-beta2 is the reason. I'll take a look.

**Comment by SKProCH** [comment]
Seems like this is exclusive 11.1.0-beta feature and wasn't accessible within 11.0.*.
So, probably I've should start a new branch to target new avalonia version.

**Comment by LyleRolleman-plst** [comment]
That would certainly be welcome as we do need the beta branch features and I get the impression the beta will be moving into general release very soon

**Comment by LyleRolleman-plst** [comment]
Any movement on this?

11.1.0 is in rc1 now, but even a nightly build with the new stuff would be welcome at this point

**Comment by SKProCH** [comment]
Currently I don't have time for this, sorry. Probably this weekend I'll do it. Also, I've already looked at Avalonia updates, perhaps you can copy-paste the new control style and make it work this way, until the update from my side. 

P. S. PRs also highly appreciated.
