### ISSUE TITLE
Proper FontFamily setting

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaCommunity/Material.Avalonia#407]
### Discussed in https://github.com/AvaloniaCommunity/Material.Avalonia/discussions/406

<div type='discussions-op-text'>

<sup>Originally posted by **PRNDA** October  7, 2024</sup>
Hey everyone,
I want to replace the default font in Material Avalonia globally. I have googled around for a while, but nothing useful has been found.</div>

**Comment by PRNDA** [comment]
The default font is defined as a FontFamily resource name `` in [Material.Styles/Resources/Themes/FontFamily.axaml](https://github.com/AvaloniaCommunity/Material.Avalonia/blob/master/Material.Styles/Resources/Themes/FontFamily.axaml).

I tried creating resources with the same name in `Application.Resources`, but this didn't work.

```
<Application>
  <Application.Styles>
    <themes:MaterialTheme BaseTheme="Light" PrimaryColor="Green" SecondaryColor="Blue" />
  </Application.Styles>

  <Application.Resources>
    <FontFamily x:Key="MaterialDesignFonts">
      Microsoft Yahei, 微软雅黑,Simsun, SimHei, PingFang SC, 苹方-简, 宋体-简, 宋体, Microsoft JhengHei, Microsoft JhengHei UI, $Default
    </FontFamily>

  </Application.Resources>
</Application>
```


Screenshot:
![image](https://github.com/user-attachments/assets/faa0e083-344e-451e-8953-3a3ce8216c0c)

**Comment by mehaifeng** [comment]
How about Button font? it can't setting font like your example.

**Comment by mehaifeng** [comment]
I tried this, but did't work.
```
		<Style Selector="Button.Content">
			<Setter Property="FontFamily">
				Microsoft YaHei
			</Setter>
		</Style>
```
		
		the only way I can fix this, is set the button's content as a TextBlock.
		
		like:
```
				<Button
					Grid.Column="0"
					Height="35"
					HorizontalAlignment="Left"
					Classes="light"
					Command="{Binding AddCroppingConfigCommand}"
					CommandParameter="{Binding ElementName=DragCanvas}">
					<TextBlock Text="ABCDEFG"/>
				</Button>
```

**Comment by SKProCH** [comment]
Yes, you need to target AccessText inside of a Button with a selector somewhat like this: `Button.Content AccessText`. This will change when this issue will be fixed.
