### ISSUE TITLE
DataGrid can not be showed on web platform

### ISSUE THREAD

**Issue by ismlsmile** [AvaloniaCommunity/Material.Avalonia#410]
### Usage Information

3.7.4/11.1.4/Windows-Web

### Description

DataGrid can not be shown on web platform, but can be shown on desktop.
[DataGridSample.zip](https://github.com/user-attachments/files/17523761/DataGridSample.zip)

### Reproduction Steps

see the demo project

### Expected Behavior

work ok on web platform

### Actual Behavior

do not show

### Could you help with a pull-request?

No

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SKProCH** [comment]
Probably some bug with autoimporting styles or trimming.

Workaround is manually include DataGrid styles in app.axaml:
```xaml
<Application ...
  xmlns:dataGrid="clr-namespace:Material.Avalonia.DataGrid;assembly=Material.Avalonia.DataGrid"
  ...

  <Application.Styles>
    ...
    <dataGrid:MaterialDataGridStyles/>
```

**Comment by ismlsmile** [comment]
it is ok, thanks

**Comment by SKProCH** [comment]
Since currently there is no proper way to debug this, I've added info about to DataGrid wiki page: https://github.com/AvaloniaCommunity/Material.Avalonia/wiki/DataGrid
