### ISSUE TITLE
SelectedItems missing

### ISSUE THREAD

**Issue by digitaldias** [AvaloniaCommunity/Material.Avalonia#411]
### Usage Information

11.1.4

### Description

To complement `SelectionMode="Extended"` please let us bind a collection to a `SelectedItems` observable collection.

### Reproduction Steps

No steps to reproduce

### Expected Behavior

Simply binding to a `SelectedItems` (plural) property

### Actual Behavior

The property does not exist

### Known Workarounds

Manually synchronizing selected items to `xxx_SelectionChanged` is tedious and shouldn't be needed. 

### Could you help with a pull-request?

No

### Is there an existing issue for this?

- [x] I have searched the existing issues

**Comment by SKProCH** [comment]
Hello. Which control are you talking about?

**Comment by digitaldias** [comment]
Apologies, it's the DataGrid

**Comment by SKProCH** [comment]
DataGrid is Avalonia control, so this issue should be reported to AvaloniaUI. Material.Avalonia only provides custom styles for controls.
