### ISSUE TITLE
ContextMenu Broken: KeyNotFoundException: Static resource 'MaterialAccessText' not found.

### ISSUE THREAD

**Issue by Trueber** [AvaloniaCommunity/Material.Avalonia#421]
### Usage Information

v3.9.0

### Description

When opening Context Menu, Application Crashes with `KeyNotFoundException: Static resource 'MaterialAccessText' not found.`

### Reproduction Steps

In Demo, right click on an element that has a context menu

### Expected Behavior

Open Context Menu

### Actual Behavior

App Crash

### Regression?

Works in v3.8.0

### Could you help with a pull-request?

No

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Trueber** [comment]
https://github.com/AvaloniaCommunity/Material.Avalonia/blob/5a04af8bc82d185425ad54d5f5566cfa4038d2a7/Material.Styles/Resources/Themes/MenuItem.axaml#L60 -> `"{StaticResource MaterialAccessText}"` does no longer exists since fc0927ba46ce2c492e27efe664e3e06d3b0855b0

**Comment by SKProCH** [comment]
Yeah, thanks for noticing!
