### ISSUE TITLE
Add bottom navigation control

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaCommunity/Material.Avalonia#48]
![image](https://user-images.githubusercontent.com/33497292/96253159-c72f5100-0fbb-11eb-8325-b87caa064e5d.png)

**Comment by ameliadiedrich** [comment]
If it isn't already in progress, I would like to take care of it.

**Comment by SKProCH** [comment]
It can be implemented via TabControl, so i closing this issue. If someone still want to contribute to it - feel free to ping me or create a new one
