### ISSUE TITLE
Rectangle Size of CheckBox

### ISSUE THREAD

**Issue by Junaid-Amjad** [AvaloniaCommunity/Material.Avalonia#77]
This point is related to the checkbox, now i have checked the checkbox in `master` and `dev` branch. In both of them, it is working fine. But when i use it on my project, its size is not big as seen on the documentation. Am i missing something?  

![Checkbox](https://user-images.githubusercontent.com/75033105/106458014-9b27d500-64b1-11eb-880b-3b0d81464120.png)

**Comment by appleneko2001** [comment]
Can you try `assist:SelectionControlAssist.Size="24"` ? it will affect the sizes of CheckBox.

![](https://user-images.githubusercontent.com/38249047/106629063-cac40380-65bd-11eb-81ce-ddd79ca3ff62.png)

![](https://user-images.githubusercontent.com/38249047/106630046-d06e1900-65be-11eb-9952-91351ead0d00.png)

Do not forgot to add depend `xmlns:assist="clr-namespace:Material.Styles.Assists;assembly=Material.Styles"` to root element parameters

![](https://user-images.githubusercontent.com/38249047/106629420-28f0e680-65be-11eb-815d-5de4a24c33a6.png)

**Comment by Junaid-Amjad** [comment]
Thanks it is resolved.

**Comment by sedwick2048** [comment]
This did not work for me.  Any updates or other options?  Too bad [NormalRectangle](https://github.com/AvaloniaUI/Avalonia/blob/master/src%2FAvalonia.Themes.Fluent%2FControls%2FCheckBox.xaml#L45-L46)'s `Height` and `Width` aren't set by dynamic resources I can override at the app level...

**Comment by SKProCH** [comment]
> This did not work for me. Any updates or other options? Too bad [NormalRectangle](https://github.com/AvaloniaUI/Avalonia/blob/master/src%2FAvalonia.Themes.Fluent%2FControls%2FCheckBox.xaml#L45-L46)'s `Height` and `Width` aren't set by dynamic resources I can override at the app level...

You can probably create a PR with that change. Or open another issue, i'll implement it when i have some free time.

**Comment by appleneko2001** [comment]
> This did not work for me. Any updates or other options? Too bad [NormalRectangle](https://github.com/AvaloniaUI/Avalonia/blob/master/src%2FAvalonia.Themes.Fluent%2FControls%2FCheckBox.xaml#L45-L46)'s `Height` and `Width` aren't set by dynamic resources I can override at the app level...

The height and width properties are defined directly, not styles-affected since they are is in source code. Only you can do to replace them is change the whole `ControlTemplate` tree
Kinda traditional change but it will works
