### ISSUE TITLE
Improve Menu and MenuItem

### ISSUE THREAD

**Issue by appleneko2001** [AvaloniaCommunity/Material.Avalonia#78]
As #75 mentioned, our styles library is still have some issues on MenuItem and Menu widgets. Issues has solved in dev-branch, but still required some improvements and fixes. For example, fix padding of MenuItem in Menu widget.

**Comment by matthewstrasiotto** [comment]
At the moment, all of my MenuItem's Click events seem to be consumed by PART_HeaderPresenter. Running 2.2.0
