### ISSUE TITLE
Circle ProgressBar

### ISSUE THREAD

**Issue by aboimpinto** [AvaloniaCommunity/material.avalonia#91]
I picked the demo project and add the class "Circle" to the ProgressBar and I see no changes in the layout 

![image](https://user-images.githubusercontent.com/1231687/119526822-04dd2f00-bd80-11eb-949f-2f44dae99d25.png)

and the result
![image](https://user-images.githubusercontent.com/1231687/119526882-14f50e80-bd80-11eb-9539-e90b87ff2d22.png)

why the correct style is not being loaded?

**Comment by SKProCH** [comment]
@aboimpinto The demo project looks different now. Are you sure you pulled the master branch?

**Comment by aboimpinto** [comment]
I think I have an old version of that ... I will check with the new version

**Comment by SKProCH** [comment]
It looks like the issue has been resolved. If not, feel free to reopen issue.
