### ISSUE TITLE
Dialogs Rendering, WindowStartupLocation.CenterOwner and arm-linux

### ISSUE THREAD

**Issue by Alocin1982** [AvaloniaCommunity/material.avalonia#92]
Hi everybody!
First of all, thank you all for the great Job!
I've some questions and concerns about  WindowStartupLocation.CenterOwner on arm-linux (Raspbian, in this case) and the difference between rendering of Window (and Dialogs) on Windows 10 and Raspbian.
This is my situation:
1. the UserControl generate a new Window ( WindowStartupLocation.CenterOwner ) and lunch it.
2. the Window contains a new UserControl, with its ViewModel in and some methods...
3. On click event, I call the Avalonia Dialog...

This is the result:

![AVALONIA](https://user-images.githubusercontent.com/58053265/123553806-a095fc80-d77d-11eb-8ff1-324de14b0254.png)

Obviously, the Window 10 version is the result I'd like to see on Raspbian too... 
What did I miss?

This is the code I've in the Program.cs file:

```
public static void Main(string[] args) {
	BuildAvaloniaApp().Start(AppMain, args);
}

public static AppBuilder BuildAvaloniaApp()
{
	return AppBuilder.Configure<App>()
		.UsePlatformDetect()
		.With(new X11PlatformOptions
		{
			EnableMultiTouch = true,
			//UseDBusMenu = true,
			UseGpu = true,
			OverlayPopups = true

		})
		.With(new Win32PlatformOptions
		{
			EnableMultitouch = true,
			AllowEglInitialization = true
		})
		.UseSkia();
}

private static void AppMain(Application app, string[] args)
{
	MainWindow = new MainWindow();
	app.Run(MainWindow);
}
```
Is it a known issue...or is it only my "inexperience"?
Thank you in advance for your reply...

**Comment by SKProCH** [comment]
Seems like this is an Avalonia issue. 
Please open another issue at Avalonia repo: https://github.com/AvaloniaUI/Avalonia/issues
