### ISSUE TITLE
Can add example for DialogHost?

### ISSUE THREAD

**Issue by unofficialdev** [AvaloniaCommunity/Material.Avalonia#94]
Can add example for DialogHost?

**Comment by SKProCH** [comment]
Yes, I will try to do it soon.
For now, you can look at the documentation and demo application here:
https://github.com/AvaloniaUtils/DialogHost.Avalonia

**Comment by SKProCH** [comment]
I've added some of examples to demo app in f7469d96c75dae812b382fcff7d714500321a24b and finally add [DialogHost.Avalonia](https://github.com/AvaloniaUtils/DialogHost.Avalonia) to project
