### ISSUE TITLE
How to set shadow depth?

### ISSUE THREAD

**Issue by wberdowski** [AvaloniaCommunity/material.avalonia#96]
Hello. I'm trying to set a shadow depth of a card in xaml, but so far with no luck. Is it even possible? Thanks in advance.

**Comment by SKProCH** [comment]
Hello, @wberdowski 
Yes, it is possible. Just set `ShadowAssist.ShadowDepth` for Card.
For example: 
```
<styles:Card assists:ShadowAssist.ShadowDepth="Depth5">
    My card content
</styles:Card>
```
will look like this:
![image](https://user-images.githubusercontent.com/29896317/126046941-ee44345d-89f5-4c7e-9669-65611d4a13e0.png)
