### ISSUE TITLE
Datagrid scrollbar style

### ISSUE THREAD

**Issue by wberdowski** [AvaloniaCommunity/material.avalonia#97]
Hello. I was wondering is there a way to change datagrid scrollbar style to classic (as seen in scrollviewer demo), and remove the remaining space between scrollbar and right border of the datagrid?

![image](https://user-images.githubusercontent.com/10144015/127032926-607c1c58-3721-4804-97c4-c353b827a782.png)

**Comment by SKProCH** [comment]
Hello, @wberdowski 
There is currently no way to bring back the classic scrollbar style, but I will add it.
As for the empty space on the left, I think this is a bug. I will try to fix it soon.
