### ISSUE TITLE
Floating label for filled ComboBox and outlined style implementation request

### ISSUE THREAD

**Issue by wberdowski** [AvaloniaCommunity/Material.Avalonia#98]
Please add floating label for filled ComboBox and outlined style if possible.

![image](https://user-images.githubusercontent.com/10144015/127146164-5010c968-59b2-4abe-990b-496c9d1fedc3.png)
![image](https://user-images.githubusercontent.com/10144015/127146205-edc69dfd-838e-484a-9067-682fa7256283.png)

**Comment by appleneko2001** [comment]
Sorry for a long waits!
I added outlined combo box style from scratch
![image](https://user-images.githubusercontent.com/38249047/140293387-a7d0746d-e13f-4bd3-a966-aabdf7074757.png)
![image](https://user-images.githubusercontent.com/38249047/140293418-4cd3e0ab-4454-42b2-88ee-52225cd30a07.png)
![image](https://user-images.githubusercontent.com/38249047/140293445-fee3156a-b5c9-4d59-9bb4-cea20104c2a4.png)
